nushell/reedline

src/main.rs

This pull request allows you to exit the repl by pressing Ctrl + d ( or Cmd + d on Mac), this also prints 'exit' in a new line prior to exiting.

Implement EOF

---

src/line_buffer.rs

This PR also makes word movement skip multiple consecutive non-word characters (word boundaries) in a similar way to how bash/readline do it.

Use Unicode words for movement

---

src/line_buffer.rs
src/main.rs

This PR provides a very simple history implementation by saving buffers into a `VecDeque` when they are "confirmed" by pressing enter. The history currently allows 100 entries, which can be changed by changing the `HISTORY_SIZE` constant in `main.rs`.  
Navigation through the history works by pressing Up/Down arrow keys and feels pretty much the same as in bash or zsh. The implementation comes with a little bit of code duplication that I left there intentionally since I didn't want to take the fun of doing cool refactorings from the stream ;) 
If you want, I could of course improve that implementation by moving repainting of the current line buffer into a separate method or something like this. Just let me know!
The current implementation doesn't support persisting the history on disk for …

Simple history implementation

---

TODO.txt
src/line_buffer.rs
src/main.rs

This finishes the refactor that moves us onto repainting logic. This greatly simplifies what we need to manage by separating the movement and edit logic from the drawing logic.

Unicode movement, pt 2

---

src/line_buffer.rs
src/main.rs

- More keys for moving around.
- `Ctrl+k`, `Ctrl+u`, `Ctrl+w`, and `Alt+d` cut text that can be pasted with `Ctrl+y`.
- Fixes a bug with backspace. Before when the insertion point was 0, but the buffer wasn't empty, it would still delete characters as if pressing delete.

Implement several new commands

---

src/main.rs

If ran with `cargo run -- -k` reedline with execute in diagnostic mode in order to show you the events that are captured from the keyboard. This is just a quick hack that allows you to see if crossterm can see the events.
If ran with `cargo run` reedline executes normally.
No work was done to formalize command line parameter parsing. This is just a quick hack to help me figure out that iterm2 appears to be eating my up and down arrow event on my mac.
Looking at the diff, it looks like a lot of code changed but i really only added one fn `print_events` and a few lines in `main`. The rest are `fmt` changing the format.

add diagnostic routine with cmd line arg

---

src/engine.rs
src/main.rs

Reuse outer Result for error handling only pass the special case
signals.

Minimal enum to address #18

---

src/diagnostic.rs
src/main.rs

* move `print_events` to it's own diagnostic crate to declutter main.rs.
* cleanup a bit of code

small refactor

---

src/engine.rs
src/history_search.rs
src/main.rs

This PR implements a basic reverse search through history mapped to `Ctrl-R`. It behaves in a similar way to bash/readline.

Implement basic history search

---

src/engine.rs
src/prompt.rs

When there isn't enough room for both the left and right prompts, only
show the left one. Also truncate the left prompt if it's too wide.

Simplify prompt code and handle narrow terminals

---

src/engine.rs

To resemble the behavior of the typical shells check if the last command was identical and ignore repeat calls

Only append unique new lines to history

---

src/engine.rs
src/line_buffer.rs

`Deref` no longer makes sense for `LineBuffer` since it can have multiple lines.

Remove Deref implementation and other refactorings

---

src/engine.rs
src/history.rs
src/history_search.rs
src/lib.rs

* Encapsulates the up/down arrow browsing
* Still fully in-memory but easy to add file based constructors and
flushing
* No further integration with the statefulness of the Ctrl-R search
(yet)

Extract history management into struct

---

src/engine.rs
src/main.rs

Make the return after a succesful entry part of `Reedline.read_line`'s
contract

Simplify prints and newline after `read_line()`

---

src/engine.rs
src/history.rs
src/history_search.rs
src/lib.rs
src/main.rs

History has a new constructor to remember a file to read from / write to.
Writing is deferred to the Drop.
Binary supports history file via `REEDLINE_HISTFILE` env variable
Additional changes:
Inverted the ordering of the history VecDeque to simplify file IO and
history internals. This makes the search code slightly more brittle.
Addresses #40

Support history file

---

Cargo.toml
src/clip_buffer.rs
src/engine.rs
src/lib.rs

The clipboard crate breaks the CI in a non GUI context. Make use of it
optional by feature flag `system_clipboard`.
Clipboard could be changed during runtime based on trait.
Additional fix: read back from system clipboard

Refactor Clipboard behind feature flag

---

TODO.txt
src/engine.rs
src/history.rs
src/lib.rs
src/line_buffer.rs

This adds two separate bits of functionality from the stream:
* Resize now properly re-renders the prompt and user input
* History up/down navigation will use the prefix of the search typed by the user before using up/down. This matches fish's prefixed history navigation

Add resize logic and history prefix

---

src/engine.rs

With the [new commit](https://github.com/jonathandturner/reedline/commit/e0714819e47463c0b7b81d33649b6f1e6ad9127e), the KeyModifiers::SHIFT case was not handled in read_line_helper function inside engine.rs; the choice was either to map all the individual characters in the default_keybindings function within keybindings.rs or to handle the case along with the normal characters; since there were no particular reasons to choose the first option I chose the fastest.

Fix unhandled shift case

---

README.md
src/engine.rs
src/enums.rs
src/history.rs
src/keybindings.rs
src/lib.rs
src/line_buffer.rs
src/prompt.rs

* Small cleanup stuff
* Tests for the new up/down prefix search
Potentially opinionated:
* Make the reset of the history cursor to now part of the `History.append()` contract
* To slim down `src/engine.rs` extract the `EditCommand` and `Signal` enums into a new module

Various proposed refactors

---

src/engine.rs
src/main.rs

Make sure to flush before we check for the prompt position. Fixes the prompt in Windows

Fix Windows prompt

---

src/engine.rs
src/line_buffer.rs

https://github.com/jonathandturner/reedline/issues/61#issuecomment-864374303
The basic idea here is to pull out the functionality of editing into `line_buffer`.

Extract operations on buffer into line buffer

---

Cargo.lock
Cargo.toml
src/history.rs
src/line_buffer.rs

This improves the test diff output a lot and consequently makes going through diffs a joy! Attaching a screenshot to showcase the difference this will make.
ref: https://github.com/jonathandturner/reedline/pull/71#discussion_r655307424

Add pretty_assertions lib

---

src/engine.rs
src/prompt.rs

The idea here is that what we want to display on the screen which can impact the prompt should be available as part of the prompt's interface.
So here are the things that can impact what we show with our prompt
- The line-editor can either be in Emacs mode or VI modes (for now) [These are exclusive to one another]
- The line-editor can be either in editing a command or searching history mode [These two states are also exclusive]
- Lastly, the command can be either single-line or multi-line.
Now all these variables can happen together (i.e. they form a cross-product)
- example 1: You can be in vi-normal mode and be editing history search term and that particular term earlier resulted in a multi-line command. (So, we need to showcase all these three variations together)
one way to do this …

Extending PromptMode

---

src/engine.rs

This happened, because the `prompt` would be drawn at the `origin`, which was determined to be at the `position()?`, which was in the previous line. 
Now, move one line downwards before determining the `origin`.

fix: overwriting of line #76

---

src/engine.rs
src/lib.rs
src/main.rs
src/prompt.rs

Move out of `Box<dyn Prompt>` by using `&dyn Prompt`.
Also use `Cow<str>` instead of `String` for the `Prompt` return types.
Both of this changes permit the use of reference but most importantly, it avoids unnecessary clones.

Improve Prompt trait and it's handling

---

src/engine.rs
src/lib.rs
src/painter.rs

From https://github.com/jonathandturner/reedline/pull/62 > https://github.com/jonathandturner/reedline/pull/62#issuecomment-864614387
> Extracting the Painter seems to absolute clean up some clutter and makes changes to output code centralized. Full endorsement from my side.
Future thought: Maybe the Painter could also do the bookkeeping on the terminal positions regarding where the current prompt started/where the current offsets are (in this case maybe named TerminalOutput) (need to be called on resize)
With a good design it is probably reasonable to hand out exclusive references of the Painter to (plugin) components.

Extract screen painting stuff into a separate struct

---

src/keybindings.rs

Let ctrl+backspace and ctrl+delete also work on words

Let ctrl+backspace and ctrl+delete also work on words

---

src/engine.rs
src/main.rs
src/painter.rs

* tool for event tracking is only relevant for testing -> main
* unnecessary enable_raw_mode call
* we don't enable mouse mode yet
* clippy suggested removals of overspecified type and clone

Remove some unnecessary stuff from the engine

---

src/engine.rs
src/hinter.rs
src/history/file_backed.rs
src/lib.rs
src/main.rs
src/painter.rs

Implemented features:
- optional inside line hints
- customizable hints style
- hints from completer
- hints from history
Example:

[Add] in-line hints

---

README.md
src/enums.rs
src/history/file_backed.rs
src/lib.rs

* Make `cargo doc` happy again
* Let the `lib.rs` doc test a few constructor examples.
* Fix badges and repo links in the README

Fix eclectic docs

---

src/engine.rs
src/enums.rs
src/keybindings.rs
src/painter.rs

This adds basic multiline support. To do so, we extend the logic for up/down to check to see if we're in a multiline situation.
For up:
If we're at the top of a multiline, we go to this previous history. If we're below the top, we count off what column we're on, move up a line, then count back to that column.
Down is the same, but moving to the next line instead of previous line.

Add multiline support

---

src/engine.rs
src/line_buffer.rs

Various fixes to history execution

History fix cursor update

---

.gitignore
src/engine.rs
src/history/base.rs
src/history/file_backed.rs
src/line_buffer.rs
src/main.rs
src/painter.rs

Fix the history behavior (#94)

---

src/engine.rs
src/enums.rs
src/keybindings.rs
src/lib.rs
src/line_buffer.rs

**Simple undo and redo**
**Cursor position restored after CtrlA-CtrlE with undo and redo**
**Undo and redo with middle line changes**

[Add] CtrlZ (undo) and CtrlG (redo) features

---

src/engine.rs

Allow pressing enter to send the history first try.
Fixes #117

Fix enter during history traversal

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/engine.rs

I wanted to create this on the branch that I have requested to merge but looks like I can't really do that as that branch does not exist in this repo. (Sigh: github should really allow for creating PRs over other PRs :P)
Anyway, this is a simplification of pulling out the undo and redo functionality into the editor struct whilst also simplifying it a bit.
**NOTE TO Reviewers: #128 does most of the work on which this build on. Only take a look at the last commit in this PR**

Pull undo redo to editor

---

src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/mod.rs
src/engine.rs
src/enums.rs
src/lib.rs
src/main.rs
src/painter.rs

I have done some refactors along the way. Let me know your thoughts on this.
This could have been 4-5 separate PRs, getting them reviewed/merged individually would have taken some time, so I just clubbed them together to save some time. (The squashing merge of PRs also makes it hard to rebase, otherwise, that could have saved a lot of trouble and I would have managed to do multiple PRs - This might just be a lack of knowledge on my side, if there is an easy way to rebase with the squashed stuff please do tell me.). 
Meanwhile here are all the things that this PR tries to do
`Hinter` has logic that is more than just display specific so it does not make sense for it to be a part of `Painter` (A component that is supposed to only care about screen painting operations). Though the same can …

Pull some events from EditCommand to ReedlineEvent

---

Cargo.lock
Cargo.toml
src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/mod.rs
src/engine.rs
src/enums.rs

This PR intends to add basic tests to the emacs edit mode.
There are two tests that are marked ignore, which I am unsure what they should be. Please add details on the desired behaviuor.
I personally think that 
- we should be able to override keybinds so it will require some work on the `KeyBinding` struct.
- I am not too sure what the default behaviour should be in-case of Events that don't have any definition. I was thinking of returning a default IGNORE event. Ideally, we should log the details along with doing nothing for that. Would like to know what others think about this.

Add tests to emacs and vi edit mode

---

src/completion/tab_handler.rs
src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/engine.rs
src/painter.rs

This makes working at the last line during a multiline a bit cleaner. Both up/down and new lines should now flow to the next line and properly scroll the input if you're at the bottom of the terminal.

Multiline improvements

---

src/painter.rs

This fixes the rendering of a multiline where we end with a newline during a line continuation.

Improve rendering of multiline

---

src/completion/base.rs
src/completion/default.rs
src/completion/mod.rs
src/completion/tab_handler.rs
src/core_editor/line_buffer.rs
src/edit_mode/keybindings.rs
src/engine.rs
src/enums.rs
src/lib.rs
src/main.rs
src/prompt.rs

- `Ctrl+C` and `Ctrl+D` did not work after the changes in #138 and #146
- Fixed by only registering the `ReedlineEvent` and defering
potentially necessary edits to the `handle_event` stage
- Defined their behavior for the reverse history search
- Corrected interactions with undo (as best as I could understand it)
- Reverse history search did not allow for browsing through its results
- Fixed `handle_history_search_event` and simplified the cases
- Register undo steps for the reverse history search (when entering and
leaving via enter)
- Added comments to similar sounding methods and variants (UPDATE IF
NECESSARY!)
- Moved the repaint stuff closer together in engine.rs for better
readability
- Noncritical stuff that caught my eye

Fix CtrlD/CtrlC and reverse-history-search + stuff

---

src/core_editor/editor.rs
src/engine.rs

Minimal change to make undo machinery of `Editor` more explicit.

Clarify method names for undo-interface

---

src/engine.rs

Appended an Option<u64> to Reedline struct that allows library users to customize the time waited between repaints.  It is interpreted as milliseconds, and if it is 'None', then no repainting occurs.  Added corresponding builder function.
Ideally, it would be friendlier if we could disable repainting dynamically, especially, when the prompt is not visible, or on 'MouseEventKind::ScrollUp'.  Unfortunately, my terminal (xfce4) would not report mouse events, so I couldn't get that to work.

Builder to customize and disable idle animations

---

src/engine.rs

To avoid issues with incoming resize events (#166) and improve performance in certain situations (pasting text via terminal facilities) restructure the event input processing:
- Drain all crossterm events currently available
- Prioritize the last resize and discard intermmediates
- Join all EditCommands to be processessed together before handing them to the internal event handler which will trigger a repaint

Improvements to handling of incoming events

---

src/engine.rs
src/painter.rs

Sorry: Still new to all this Github machinery!  
But, have eliminated the need to create a new String at each character insert.
Since we have separated the manipulation of the underlying buffer from the act of painting it, there's no harm in inserting the character into the buffer, then inspecting that.
Moreover, tried to make the code for 'insert char' more readable, and to simplify the interfaces.

`fn queue_buffer` probably didn't mean to flush; Simplified engine->insert_char and removed the need to create a String at each insert.

---

src/engine.rs
src/styled_text.rs

As requested in #112, I tried implementing a simple way of printing the multiline continuation prompt.
Note that this works for multiline blocks only. Opening a block by using a parenthesis, a bracket or a brace, and going to the new line prints the continuation prompt. Text wrapping on the next line does not.
This might actually be considered a feature, since it allows to visualize how the input was actually inserted in the buffer; however, it is visually inconsistent.
As another issue of the implementation, the prompt style is re-created and used in the `render_around_insertion_point` function (see `styled_text.rs`, line 38). This is currently hard-coded since the prompt styling is handled differently when printing the main prompt: it uses `crossterm`'s `Color` instead of …

Simple multiline continuation prompt

---

src/painter.rs

Avoids jumping cursor to the prompt on full repaints of the standard
buffer. Does not completely remove a perceptable flicker at the fixed
position if animation is active.
Partially addresses #174 as other cases still need to be checked for
cursor updates

Fix cursor flickering for full repaint

---

src/engine.rs

Addresses https://github.com/nushell/engine-q/issues/386
Breaks the API for variable refresh times, standardizes on one second
and simply optionally disables the automatic repaint.

Fix busy polling when animation is disabled

---

src/engine.rs
src/styled_text.rs

As requested [here](https://github.com/nushell/reedline/pull/184#issuecomment-977800119) and as a direct follow-up to #184, I tried to "forward" a Prompt parameter to the rendering functions, so that the `render_prompt_multiline_indicator` was available.
I am not sure about how I used `Cow<str>, or that,  from a design standpoint, passing in the multiline prompt is the best idea. I am available to implement any variation, in order to make it better, of course!

Forwarding Prompt's multiline indicator

---

src/engine.rs
src/enums.rs
src/lib.rs

Address #190
Formalize the undo role of different edit commands via exhaustive
matching
Open questions:
- Undo behavior of pure moves #193 
* Do we want to make them undoable
* Do we have to register them for accurate undos of true edits
- Manual backspace and delete #194 
* Do we want to coalesce them if a whole word is manually deleted?

Improve undo of EditCommands

---

src/completion/base.rs
src/completion/default.rs
src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/edit_mode/base.rs
src/engine.rs
src/highlighter.rs
src/history/file_backed.rs
src/prompt.rs
src/styled_text.rs
src/validator.rs

- remove unused members, found after 1.57
- semicolon termination in void blocks
- other clippy pedantic prompted fixes

Fix clippy style and remove unecessary stuff

---

src/main.rs

Only affects behavior of demo app
Additional line was a crutch introduced to counteract misbehavior fixed
in #77
Similar behavior was already sneaked into engine-q with https://github.com/nushell/engine-q/pull/508

Remove additional line on line clear via Ctrl-C

---

src/engine.rs

Panicking inside reedline (or bubbling up an Err inside reedline's
critical sections that gets unwrapped/expected by the hosting
application) leaves the terminal in a bad state. Workaround that should
also work without cooperation by the consumer would be to include a call
to `disable_raw_mode` in the `Drop` trait. With standard stack-unwinding
panics will call the drop.
Calling `crossterm::terminal::disable_raw_mode` twice seems to be fine
if the program started in non-raw mode (under linux)
@jntrnr or @fdncred could you check if running the demo does not cause a problem due to disabling the raw mode twice

Disable raw mode with `Drop` for panics

---

src/engine.rs
src/enums.rs
src/hinter.rs
src/main.rs

This lets you hit the tab key and accept the current history hint. If there is no hint, you'll get the normal completions.

Apply history on tab

---

src/engine.rs
src/enums.rs

A paste event is defined which allows to copy and paste into a prompt faster

defining paste event

---

README.md
src/engine.rs
src/highlighter.rs
src/lib.rs
src/painter.rs

Keeping correct track of coordinates on the terminal screen is paramount to not cause artifacts. Those calculations have to take into account wrapping, new lines and resizing of the terminal. 
In several locations in `src/engine.rs` such computations are performed and then executed in the `Painter`. Some magical comparisons and offsetting operations are not clearly documented, making it difficult to debug problems and adding new functionality that might require moving around multiple lines.
* Rename `PromptWidget` to `PromptCoordinates`
* Explicit setters for `PromptCoordinates`
* Set offset implicitly on `Reedline::full_repaint`
* move the terminal size and prompt coordinate information into `Painter`
* Account for some issues with history search
* Make sure that the prompt is painted on …

Attempt at consolidating offset calculations and streamlining the painting

---

src/engine.rs
src/hinter.rs
src/history/base.rs
src/history/file_backed.rs

- Move history newline escape to the file IO
This avoids that the newline escape character can be found via search and thus mess upt the search results, also makes the API internally simpler
- Remove unnecessary optional history allocation
Very minor potential improvement

Improve history internals

---

src/edit_mode/vi/mod.rs
src/engine.rs

Making vi insert mode default when starting terminal

vi insert mode default

---

src/engine.rs

Additional autosuggestion (history) hints are confusing while
navigating through the history.
Example history:
```
hello test
hello
something else
hello world
whatever
```
- Type `h`
- Press up arrow
- Prefix based history search will return `hello world`
- Press up arrow again
- Previously `hello <hint>world</hint>` now just `hello`

Disable hints during history traversal

---

src/core_editor/clip_buffer.rs
src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/core_editor/mod.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/parser.rs
src/engine.rs
src/enums.rs

- Moves to start and beginning of the line
- Make start and end of buffer available for move via `Ctrl-Home` and
`Ctrl-End`
- Support vi style cutting of whole lines in the cut buffer.
- add vi style `p` after paste in addition to before cursor paste with
`P` or in emacs mode
- Enables vi style `dd` and paste
- Make sure the line to end cut and clear operations work only on the
line

Make the editing operations aware of multiline

---

src/core_editor/editor.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/parser.rs
src/engine.rs
src/painter.rs

The prompt moves and gives space to hint when it is located at the bottom. 
the prompt moves upwards based on the suggestion
Note: This also removes the issue when the suggestion was being redrawn every second

prompt moves based on hint

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/engine.rs

- Made move up and move down unicode safe
- Added the option to constrict the char search (vi `f` `F` `t` `T`) to
the current line as usual in vi
- Improved test coverage

Improve correctness of move operations

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/engine.rs

There are latent concerns about unicode correctness, but as long as
crossterm/hints are providing correct chars/strs this is neither a security risk
(no unchecked/unsafe string ops on our side) nor
a DoS risk.

Insert strings directly

---

README.md
src/engine.rs
src/highlighter/example.rs
src/highlighter/mod.rs
src/highlighter/simple_match.rs
src/lib.rs
src/main.rs
src/painter.rs
src/styled_text.rs

Fixes `history_search_paint`:
- Fix unnecessary clear of single line
- Ensure LF to CRLF in search results
Fixes `Painter`:
- Make sure that Color is cleared after prompt (Currently depends on
Highlighter to provide a new color)
- Remove unnecessary fn
Introduce simple highlighting of the search term in the search result

Improve and highlight history search

---

src/context_menu.rs
src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/mod.rs
src/edit_mode/vi/vi_keybindings.rs
src/engine.rs
src/enums.rs
src/lib.rs
src/painter.rs

Introduces context menu for reedline. 
To activate the menu use ALT+1. This is temporal while we decide how to call the menu

Context menu

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/parser.rs
src/edit_mode/vi/vi_keybindings.rs
src/engine.rs
src/enums.rs

- Moves the big match statement for `EditCommand`s into `Editor`
- Removes the need for many `pub` wrappers around the `LineBuffer`
- Make `Left` a `ReedlineEvent` as well
- Fix left, right, up, down for vi mode

Move running of EditCommands to the editor

---

src/hinter.rs

In the hinter logic `LF` was always replaced by `CRLF` thus inserting unnecessary `CR`'s into the linebuffer that accumulate if a multiline entry is recalled via hint autosuggestion from history multiple times.
- Hexdump of history file shows contamination with `CR` (`0x0D`)
Carriage returns, that are not introduced at the end of the line as part of the painter or the OS convention, break the painting of multilines, as the cursor position might jump to the start of the multiline continuation prompt and start painting from there!

Remove superfluous insertion of carriage return

---

src/engine.rs
src/main.rs

As this function can only be called outside running
`Reedline::read_line` it is not relevant for raw mode reasons and can be
replaced by standard `println!()`

Remove `Reedline::print_line` from the API

---

README.md
src/completion/default.rs
src/completion/mod.rs
src/engine.rs
src/hinter.rs
src/lib.rs
src/main.rs
src/painter.rs

Focus the functionality of the `DefaultHinter` on providing fish/zsh-style history autosuggestions
Simplifies hinter and drastically reduces the number of allocations per `Hinter::handle` call
- (Show content after cursor when completing)
- Place the hint obligatory behind the line content
- Simplify hinter internals/capabilities
- Remove `HistoryCompleter` (was never pub)
- Fix doctest `Reedline::with_hinter`
- Add configurable character threshold for Hinter

Distill `DefaultHinter` down to history suggestions

---

src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/vi_keybindings.rs
src/engine.rs
src/enums.rs
src/hinter.rs

Hints can now be completed partially
Keybindings: `Alt-right` `Alt-f` `Ctrl-right`
Uses whitespace as token/word boundary for now

Support "token by token" hint completion

---

src/painter.rs
src/styled_text.rs

- Doc and integerify `estimated_wrapped_line_count`
- Correct and doc `line_width`
- Single alloc `strip_ansi`
- Collapse ANSI handling in wrapping

Small Painting changes to improve readability and correctness

---

src/engine.rs
src/painter.rs

Now take into account that the new cursor position might have to be at
the last line of the screen that is already used. (Was hidden when on
the last line of a multiline buffer due to superfluous `CRLF` in the
event handler)
Fixes #261

Fix after entry cursor positioning at the bottom

---

src/history/file_backed.rs
src/main.rs

Change how the history filters data. The filtered values now are sorter chronologically 
Also the keybinding for the history menu is changed to match engine q

chronological order search

---

src/engine.rs
src/painter.rs

Will only introduce a CR if LF is not part of CRLF.
Only allocates if necessary

Coerce to CRLF lazily

---

src/painter.rs

The prompt initialization was still hardcoded for the two line prompt.
Now all adaptation to account for the number of prompt lines is done
during repaint

Init prompt without superfluous line at the bottom

---

src/engine.rs
src/menu/completion_menu.rs
src/menu/history_menu.rs
src/painter.rs

- Correct allocation behavior of `coerce_crlf`
- Consolidate names to `screen_width/height`
- Simplify the `PromptCoordinate` down to the row
- Encapsulate the large buffer state readonly
- Consolidate line requirement calculion

Polishing in the painter

---

src/core_editor/editor.rs
src/engine.rs
src/enums.rs

All `repaint`/`buffer_paint` calls are removed from the event handling,
instead the `EventStatus` determines if a repaint is necessary:
- `Handled` -> repaint
- `Inapplicable` -> no action was taken, thus no need to repaint
Additionally some conditions to check and repeatedly used patterns
abstracted as methods.

Clean engine by coalesced painting and abstraction

---

src/engine.rs
src/main.rs

This adds a new configuration setting for completions that will auto-select a completion entry if the user narrows down to a single entry.
As this might surprise some users, I'm leaving it off for now. It can be configured with the builder.

Add support for quick completions

---

src/engine.rs
src/internal/query.rs
src/main.rs
src/menu/history_menu.rs

Simplifying the keybinding functions and correcting default keybindings

Keybindings functions

---

Cargo.lock
Cargo.toml
src/history/file_backed.rs

Add safe `sync` method to `History`
This method both reads from the file and writes local additions. Is safe
when multiple `History` instances try to truncate the history file on
disk.
To avoid race conditions on the file uses the `fd_lock` crate for file
advisory locks. (Inspiration for that thanks to rustyline: https://github.com/kkawakam/rustyline/blob/master/src/history.rs)
Fixes #221
- Cover history file ops with tests
- Add test for conflicting writes that should truncate
- Add safe `sync` method to `History`
- Test `FileBackedHistory` for threadsafety

Make appending and truncating history file thread safe

---

src/engine.rs
src/lib.rs
src/main.rs
src/menu/completion_menu.rs
src/menu/history_menu.rs
src/menu/mod.rs
src/painter.rs

The menu trait has being simplified to work with an event enum. These events remove the need to update twice when the `quick_completions` is true.
closes #301 and fixes some navigation issues with completion_menu

Menu events

---

src/engine.rs

Fixes the case where you have a single item in your completion list.
Previously, it would hit enter immediately without finishing the completion.
Now, it will fill out the completion and allow you to continue typing.

Fix one item completions

---

src/menu/completion_menu.rs

When there is an empty menu, the required rows should be 1 to allow space for the message to be printed

extra row for empty menu

---

README.md
src/lib.rs

Keybindings are currently configured to require the completion menu. To
use the completions you have to manually add it.
Undocumented: Changing the keybindings to use the old bash style
completions with `CircularCompletionHandler`
Track #307

Small fix to document need to configure completion

---

src/history/file_backed.rs
src/menu/completion_menu.rs
src/menu/history_menu.rs

Fixes ci fail due to new clippy lint in rust 1.59

Use chars in `str::replace` where applicable

---

src/engine.rs
src/highlighter/example.rs
src/highlighter/mod.rs
src/highlighter/simple_match.rs

Changes the `Highlighter` trait to include the position of the cursor in
the buffer. This allows it to make cursor aware highlighting such as
highlighting matching braces or code blocks
Prerequisite to address nushell/nushell#4325

Provide cursor position for highlighting

---

Cargo.lock
Cargo.toml

crossterm 0.23 seems to have introduced a regression on windows for
decoding keybindings with `ctrl` that uppercases the char.
Tracking issue crossterm-rs/crossterm#636
Might be fixed by crossterm-rs/crossterm#629

Revert crossterm: key modifier issue on win

---

Cargo.lock
Cargo.toml
src/edit_mode/emacs.rs
src/edit_mode/vi/mod.rs

Instead of moving to crossterm git, use the latest crossterm but normalise the key events to be lowercase.
For times when we need the uppercase character, detect the SHIFT modifier, and then uppercase based on that.

Better crossterm fix

---

src/engine.rs
src/menu/history_menu.rs
src/menu/mod.rs

It replaces into the prompt a history entry using the syntax `!!` or `!10`

history bang

---

src/core_editor/editor.rs
src/engine.rs
src/enums.rs
src/menu/history_menu.rs
src/menu/mod.rs

Improvements on the history commands:
- The `!!` can be undone
- The `!10` will select the entry number 10 chronologically (matches history command)
- Values from history menu can be inserted in the prompt

History improved

---

src/engine.rs

Simplifies the logic for the `!` expansion
When more expansions are required, the history menu offers more flexibility

Bang command expands only alone in buffer

---

src/menu/history_menu.rs
src/menu/mod.rs

the history menu gets next page when filtering

History menu pages

---

Cargo.lock
Cargo.toml

This updates reedline to 0.3.1 so we can use nu-ansi-term 0.45.1 in nushell

bump to 0.3.1 and nu-ansi-term to 0.45.1

---

src/menu/history_menu.rs

Since history menu ignores quick completions it needs to update when loaded

update history menu

---

src/completion/default.rs
src/main.rs
src/menu/menu_functions.rs

Fix `menu::menu_functions::find_common_string` returning wrong index when given non-ASCII strings. This should fix https://github.com/nushell/nushell/issues/4971

Fix `menu::menu_functions::find_common_string`

---

src/edit_mode/emacs.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/mod.rs

Corrects a bug where it wasnt possible to define keybindings for normal mode for NONE or SHIFT modifiers.
It also captures uppercase when using caps

Vim normal keybingings

---

src/core_editor/edit_stack.rs
src/core_editor/editor.rs
src/core_editor/mod.rs

Hey, I was looking at the #193 and wanted to pick it up. Though before I went into fixing it I decided to clean up the undo-redo logic by adding an edit stack in the mix. The benefits that I envision from this approach are 
- We were maintaining edits and a cursor in the `Editor` which seemed like a responsibility that it should not have to deal with 
- Simplifies the undo-redo logic (now we only need to think about maintaining a single stack then keeping track of edits vector and cursor 
Let me know if this is acceptable.

Edit stack

---

README.md
src/completion/default.rs
src/engine.rs
src/lib.rs
src/main.rs

The fallible std::io::Results were originally introduced for the history
file but the critical points are completely separated from the builder
pattern now.
Makes the public API nicer

API break: remove unnecessary fallibility

---

src/completion/base.rs
src/completion/default.rs
src/completion/history.rs
src/completion/mod.rs
src/engine.rs
src/lib.rs
src/main.rs
src/menu/columnar_menu.rs
src/menu/list_menu.rs
src/menu/menu_functions.rs
src/menu/mod.rs
src/menu/search_menu.rs

Changes the completion and history menu to become generic templates that can be used with different sources. These templates can be used in nushell and they could be fed using a nushell block

generic reedline menus

---

src/completion/base.rs
src/completion/circular.rs
src/completion/default.rs
src/completion/history.rs
src/core_editor/editor.rs
src/engine.rs
src/menu/columnar_menu.rs
src/menu/list_menu.rs
src/menu/mod.rs

Changes the completer trait to take a mutable reference of itself on
calling `Completer::complete`
This enables the completer to do caching or other smart things on the fly.

[API] Allow the `Completer` impl to be stateful

---

src/edit_mode/keybindings.rs

Used to delete words
Shared between vi and emacs
Fixes #383

Add Ctrl-Delete/Backspace as default keybindings

---

src/painting/painter.rs
src/prompt/base.rs
src/prompt/default.rs

This is totally up for debate. Just looking for something less boring, and less ugly blue. :) I'm up for just about any colors other than everything being the same boring blue.
that's in windows - left prompt is `green bold` (like old nushell), indicator is `cyan bold` (like old nushell), right prompt is `dark orange`. left prompt replaces `home dir` with `~` if appropriate and also changes `\\` to `/`.

change up prompt with traditional nushell colors

---

src/edit_mode/keybindings.rs

This was previously impossible, existing defaults could only be overridden.

Allow the removal of keybindings

---

src/engine.rs
src/main.rs
src/validator/mod.rs

Default constructor created a Hinter and Validator.
Disabling those required writing a noop versoin of the trait.
Now they are off by default and can be added or removed via the
"builder" pattern.

Remove `Hinter` and `Validator` from the default

---

README.md
src/core_editor/edit_stack.rs
src/core_editor/editor.rs
src/edit_mode/vi/command.rs
src/engine.rs
src/lib.rs
src/menu/mod.rs

e.g.
- making modifying, non-returning functions more obvious by `;`
termination.
- merging match arms where it improves legibility

Cleanup some stuff found by pedantic clippy

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/engine.rs
src/enums.rs
src/main.rs

Uses the system newline separator
Example in main with `Alt+Enter` (according to @fdncred `cmd-option-enter` or `shift-option-enter` on macOS to get the same key event)

Add explicit `EditCommand::InsertNewline`

---

README.md
src/engine.rs
src/enums.rs
src/lib.rs
src/main.rs
src/painting/painter.rs

**Warning API break:** removes a variant from `Signal`
- Remove the `Signal::CtrlL` as it requires explicit handling and
cooperation but we offer configurable keybindings already
- Default keybinding of `Ctrl-l` is `ReedlineEvent::ClearScreen` that
directly performs the scrollback buffer preserving clear of the current
screen.
- Add `ReedlineEvent::ClearScrollback` to perform screen clearing with
removal of the scrollback buffer. (Demo will now do that on clear as
seen in bash, zsh etc.)
Fixes #120
Helps with nushell/nushell#5089

Add better options for screen clearing

---

src/edit_mode/keybindings.rs
src/engine.rs
src/enums.rs
src/main.rs

Introduces a new event to open a line editor to edit the line buffer
Note. There is an issue that I cannot figure out. After you open the line buffer (ctr + e), edit your line and save the result, if you press `ctr+c` there is a panic in reedline. I've been looking everywhere but I cannot find where it is coming from.  Any suggestions on where that error could come from?
closes #409

line buffer editor

---

src/edit_mode/keybindings.rs
src/engine.rs

Changes the keybinding to open the buffer editor because it overrides an existing emacs keybinding

Buffer editor keybinding

---

src/menu/columnar_menu.rs

This changes the partial completion mechanism so that it only replaces the entered text when the entered text is a prefix of the suggestion. This fixes problems with the fuzzy matching (see https://github.com/nushell/nushell/pull/5320#issuecomment-1110255908).
For example:
Suggestions: `build`, `all-build`
Before this PR: `build<tab>` -> ` ` (shared prefix is empty, therefore the entered input is replaced with an empty string)
After this PR: `build<tab>` -> `build` (there are suggestions which don't share a common prefix, therefore no partial completion happens)
To avoid a worse experience with file path completion I'd suggest to also consider merging https://github.com/nushell/nushell/pull/5387 in nushell.
This PR also adds some unit tests for the partial completion mechanism.

Only partial complete suggestions when input is a prefix

---

src/painting/painter.rs

Clearing the scrollback did not work on most terminal emulators.
By reordering two ANSI control sequences, this seems to work on Linux
with most terminal emulators.
Due to a missing implementation of the exact details this will probably
not clear the scrollback under the old Windows API.
Related to the discussion in #120 and nushell/nushell#5089

Attempt fix of `ClearScrollback`

---

src/core_editor/editor.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/parser.rs
src/enums.rs

Rebased the commits from #406
- vim's 'S' binding
- copy char while deleting in vi mode
- Fixes the behavior of `x` so the removed char/grapheme can be pasted with `p`
- vim's 's' binding
- Minor clarifications
- Fix doccomments and clarify an enum variant's name
Closes  #406

Vi additions and fixes by @zim0369

---

.github/workflows/ci.yml

`cargo nextest` currently doesn't support running the doctests.
Thus, add an additional step for them with cargo's default test runner.

Add doctests back to the CI

---

README.md
src/completion/default.rs
src/engine.rs
src/lib.rs

- Fix README and lib.rs code examples
- Add missing doctests
- Fix the completion example in README
- Fix the edit mode example
- Try to run more of the doctests
- They should not block with the IO loop or do file IO as this was failing the CI

Fix README and lib.rs code examples

---

src/edit_mode/keybindings.rs

Current `Ctrl-I` is overloaded as `Tab` in the ASCII/ANSI world.
Don't use `Ctrl-U` (Conflict with emacs cut command)
Best candidate `Ctrl-o` (mnenomic "o"pen in editor) currently not bound to anything

Change keybinding for external editor

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/mod.rs
src/edit_mode/vi/motion.rs
src/edit_mode/vi/parser.rs
src/enums.rs

The 'w' motion goes to the beginning of the next word to the right, not
the end. The 'e' motion, which is introduced here, goes to the end, but
lands on the last character, not after it.

Fix vi-mode word motions

---

src/history/file_backed.rs

Amortized growing of the history based on the amount read from the file
is cheap. Allocating for the capacity is expensive and can cause OOM for
large capacities.
Fix for nushell/nushell#5593

Do not allocate eagerly for full history capacity

---

src/menu/list_menu.rs

The problem:
https://user-images.githubusercontent.com/44893716/169713547-304e506a-34d1-4a0b-913b-a21280d1ab56.mp4
The code didn't account for the index and the indicator in its calculation for the number of lines in the list_menu.
Now the unicode_width of the indicator and the number of digits of the index are accounted for.

fix: list_menu not accounting for index + indicator

---

src/painting/painter.rs

I have am using reedline on an remote shell rendering on the web. The terminal size is incorrectly reported as 0, 0 (NOT due to a bug in crossterm), which leads to divide by zero panics.
Instead of panicking, I thought maybe having a default size makes sense. 
Feel free to not merge this, I can just use this as a patch. But I think any terminal size is better than pacicking.

Use a default terminal size if reported terminal size is 0, 0

---

src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/vi_keybindings.rs

Group the common keybindings into three functions:
- `add_common_control_bindings`
- `add_common_navigation_bindings`
- `add_common_edit_bindings`
Vi normal uses the first two
Vi insert uses all of them
Emacs extends upon those

Organize the common keybindings

---

src/history/file_backed.rs

Relative: https://github.com/nushell/nushell/issues/5203
After investigate, I think `nu` will crash is because history file's parent is deleted, and it leads to file sync operation failed.
Refer to the expected behavior in that issue:
> I expected nu to ask to recreate the missing config files, like it did on first start.
I think that's too complicated to implement such feature, instead, we can make `nu` work as normal (because config is loaded to memory), we just need to create that missing directory.

Don't panic when parent directory does not exist

---

.github/workflows/ci.yml
.gitignore
Cargo.lock
Cargo.toml
src/completion/history.rs
src/core_editor/editor.rs
src/engine.rs
src/hinter/default.rs
src/history/base.rs
src/history/cursor.rs
src/history/file_backed.rs
src/history/item.rs
src/history/mod.rs
src/history/sqlite_backed.rs
src/lib.rs
src/main.rs
src/menu/mod.rs
src/result.rs

This is the third version of a history database for reedline, based on the previous discussions on Github and Discord.
- The history trait is modified to be more flexible and support all the interesting metadata:
https://github.com/nushell/reedline/blob/5fc904e0750f54a065720c1b74acecc6d208f890/src/history/base.rs#L116-L153
The FileBackedHistory was rewritten to be based on this new trait, returning errors if the user tries to filter by things it doesn't support.
Each history item stores the command line plus some additional info:
https://github.com/nushell/reedline/blob/5fc904e0750f54a065720c1b74acecc6d208f890/src/history/item.rs#L44-L64
- All the stateful cursor functionality (back, forward) is removed from the History trait and moved to a separate `HistoryCursor` struct that works with …

SQLite History (third version)

---

src/history/base.rs
src/history/item.rs
src/history/mod.rs
src/lib.rs

Makes the history querying structs and enums pub as it seems reasonable
for now. Useful to create nushells `history` command.
Might make sense to change that API to something simpler cleaner later.
Relevant to nushell/nushell#5721

Expose the `History` query functionality

---

Cargo.lock
Cargo.toml
src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/motion.rs
src/edit_mode/vi/parser.rs
src/enums.rs

Vim has motion commands over a [*word*](https://vimhelp.org/motion.txt.html#word):
> A word consists of a sequence of letters, digits and underscores, or a sequence of other non-blank characters, separated with white space (spaces, tabs, <EOL>).  This can be changed with the 'iskeyword' option.  An empty line is also considered to be a word.
And a [*WORD*](https://vimhelp.org/motion.txt.html#WORD):
> A WORD consists of a sequence of non-blank characters, separated with white space.  An empty line is also considered to be a WORD.
reedline only supported motions for *word* so if you wanted to move through hyphenated text like `git merge --no-edit main` it takes 8 *w* motions to reach the end, but only 4 *W* motions.
readline-compatible line editors support these motions 
Movement, delete, …

Add vi WORD motions B, E, W

---

src/menu/menu_functions.rs

Fix nushell issue: https://github.com/nushell/nushell/issues/5788
I think `!!` should behave like `!-1`, and for `!-1`, the result index is `1`

fix double bang

---

src/engine.rs
src/menu/menu_functions.rs

Sadly find the fix in https://github.com/nushell/reedline/pull/444 breaks `!!` in history search menu... Because `!!` will select the item with index `1`.
To avoid this, introduce `ParseAction::LastCommand` for `!!`, then `reedline` can handle `!!` and `!3` better.

introduce LastCommand variant for parse bang result

---

src/core_editor/editor.rs
src/edit_mode/vi/command.rs
src/enums.rs

This is an incomplete implementation as it omits the behaviors for CTRL-V, CTRL-E, and CTRL-Y:
> Replace the character under the cursor with {char}. If {char} is a <CR> or <NL>, a line break replaces the character.  To replace with a real <CR>, use CTRL-V <CR>.  CTRL-V <NL> replaces with a <Nul>.
>
> If {char} is CTRL-E or CTRL-Y the character from the line below or above is used, just like with |i_CTRL-E| and |i_CTRL-Y|.  This also works with a count, thus `10r<C-E>` copies 10 characters from the line below.
The similarly-named ReplaceChars is used for history substitution and
is more complicated than we need (n_chars will always be 1, string will
always be a single character string), but could be used if the extra
replace_char() function is too much.

Add vi r (replace)

---

src/edit_mode/vi/command.rs
src/edit_mode/vi/mod.rs
src/edit_mode/vi/parser.rs
src/engine.rs
src/enums.rs

The f, F, t, and T left-right motions can be repeated with the ; motion, or reversed with the , motion:
> ;
> Repeat latest f, t, F or T [count] times. See cpo-;
>
> ,
> Repeat latest f, t, F or T in opposite direction [count] times. See also cpo-;
I named these "to-till" motions as the first word of the description for the f and T motions are "To" and "Till" respectively.
Add storage for the last To or Till motion on the `Vi` struct, and pass it through to `parse_command()` so `;` or `,` can re-use it.
When a to-till motion is fully parsed the new to-till motion is stored in the `Vi` struct.
I'm not the happiest with finding a new to-till motion in the parsed command. I can't think of a better way to match it due to the `Vec`, but am open to suggestions.
It's probably reasonable to make …

Support vi mode ; and , motions

---

src/engine.rs
src/painting/painter.rs

To help repainting and resize be more stable and more inline with what terminals expect, we'll no longer repaint during a non-edit event (including resizing and animations).

Remove animations and resize repaint

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/edit_mode/vi/command.rs
src/enums.rs

> Switch case of the character under the cursor and move the cursor to the right.
vi behavior is to only swap the case of an ASCII character so this is
implementation matches that behavior

Support swtiching the case of a char with ~ in vi

---

Cargo.lock
Cargo.toml

This new crossterm version includes a breaking change to the indexing of
certain cursor move operations:
https://github.com/crossterm-rs/crossterm/releases/tag/0.24
While reedline itself might not be affected, check the code of the
consuming application that needs to match the crossterm version!

Update crossterm to 0.24

---

Cargo.lock
Cargo.toml

`rstest = 0.12` added support for asynchronous timeouts during testing
thus requiring a larger set of dependencies. Since `rstest = 0.14` this
can be disabled if not used.
Should keep build times for local or CI tests in check.

Reduce dev-deps by narrowing `rstest` features

---

src/edit_mode/vi/command.rs
src/edit_mode/vi/motion.rs

The main feedback question for this pull request is for the multi-line handling I've made it so `d0` and `d$` will only delete to the end of the **_line_**, but the previous behavior of `d$` deleted the end of the **_input_**, even for multi-line inputs.
I believe my change is more consistent with vi's behavior, but let me know if the prior `d$` behavior is preferable and I can edit accordingly.

Vi mode add support for d0, d^, c0, and c^

---

src/lib.rs

Export `crossterm::event::{KeyCode, KeyModifiers}` as our own.
This way users of the library don't have to import crossterm with the
same version explicitly to set their own keybindings.
Closes #456

Export the crossterm key types

---

src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs

Moving the edit binding to `add_common_edit_bindings` because `Ctrl+h` works in Vim's **Insert** mode as backspace. This behavior is also supported by _vi_ mode in bash.

Ctrl+h edit binding moved from emacs to common

---

src/hinter/default.rs

This PR fixes panic when using sqlite as history backend.
Fixes nushell/nushell#6251
We can reproduce the panic with the following steps:
1. `echo %` <kbd>enter</kbd>
2. `echo %%` :boom: 
[![asciicast](https://asciinema.org/a/yY3B6vWGhYptvj7j3PUkAIKTU.svg)](https://asciinema.org/a/yY3B6vWGhYptvj7j3PUkAIKTU)

Fix panic when using sqlite as history backend

---

src/engine.rs

This is necessary to avoid the problem with running `executehostcommand` keybindings in nushell right after launching it (without having run actual user-input commands yet).
Since the error types are not exposed outside of the crate, we have to use a check instead of matching on the error.

Add Reedline::has_last_command_context to allow checking if update_last_command_context will fail

---

src/engine.rs

This allows nushell to implement a command similar to fish's `commandline`:
https://fishshell.com/docs/current/cmds/commandline.html
that would allow commands run via `executehostcommand` bindings to do interesting things to the contents of the input buffer.

Allow external manipulation of the command line buffer, fixes #423

---

Cargo.lock
Cargo.toml
README.md
src/lib.rs

This came up in https://github.com/void-linux/void-packages/pull/39143#issuecomment-1239582933 while talking about bundling or not bundling deps. IMO, libraries like reedline shouldn't force using a bundled version, and if that decision is to be made at all, it should happen in the application, not somewhere deep in the dependency tree. If an application wants sqlite bundled, the application itself can add a dep on rusqlite and add the `bundled` feature, and cargo will use the bundled variant for reedline as well, via feature unification. Disabling the bundling in a similar fashion isn't possible though.
Ideally, I'd like to have an override for this available in libsqlite3-sys, but that hasn't happened yet (see https://github.com/rusqlite/rusqlite/issues/769), so the quick solution for …

Don't bundle sqlite by default

---

src/edit_mode/vi/command.rs
src/edit_mode/vi/mod.rs
src/edit_mode/vi/motion.rs
src/edit_mode/vi/parser.rs

Fixes #473
The parser has to consume the items from the iterator to be in a consistent state!
The specific issue with `.` #449 still remains open after this change.
- Move `ViToTill` logically to `motion.rs`

Fix vi character search parsing

---

src/engine.rs
src/history/base.rs
src/history/file_backed.rs
src/history/sqlite_backed.rs

This PR changes the `history_session_id` from a regular number like 1,2,3,4,5 to a systematically generated number based on the date of reedline's first commit and is expressed in nanoseconds. 
I submit this change in order to be able to generate a `history_session_id` without the need of looking anything up in the history database. This number should be pretty unique although not precisely unique. Each time you start up reedline you get a new time and therefore you get a new `history_session_id`.
I also changed the trait so that `next_session_id()` no longer exists.
I created a public function in the Reedline impl to `get_history_session_id()`. Hopefully that is enough to return it so that we can use it in nushell in order to filter on each session id which will be unique to each …

change history session_id to a systematically generated number

---

src/history/item.rs

This PR adds a small change to enable easier conversion from HistorySessionId to i64.

enable easier history session id conversion

---

src/utils/query.rs

Necessary to complete nushell/nushell#6590
(Comment: this whole module feels intricately linked to the nushell
implementation as we do not implement the string parsing in reedline)

List that space can be bound through `Char(' ')`

---

src/core_editor/editor.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/mod.rs
src/edit_mode/vi/motion.rs
src/edit_mode/vi/parser.rs
src/engine.rs
src/enums.rs

Move the `Repaint` addition outside to ensure it is always added.
Currently required to detect the mode change visually.
Take into account that only the product of the `multiplier` and `count` are relevant to execute motions.
From https://github.com/vim/vim/blob/140f6d0eda7921f2f0b057ec38ed501240903fc3/runtime/doc/motion.txt#L63-L70
> If the motion includes a count and the operator also had a count before it,
> the two counts are multiplied.  For example: "2d3w" deletes six words.
> When doubling the operator it operates on a line.  When using a count, before
> or after the first character, that many lines are operated upon.  Thus `3dd`
> deletes three lines. A count before and after the first character is
> multiplied, thus `2y3y` yanks six lines.
I discovered a limitation in how we …

Vi-Refactor: Properly parse motions separate from the actions

---

.github/workflows/ci.yml
src/painting/painter.rs

Just tested external print and noticed this issue. It's not super important, but nice to have.
Previously each external print was causing a visible flicker on at least two terminal emulators I've tested (alacritty, xfce4-terminal).
I'm not sure this is the best solution. I've looked into just removing `.flush()` in the `print_line`. The latter is used in just two places here and in printing history. It would be fine to also optimize out flush on every line when printing history, however that would likely break abstraction and make painter somewhat more stateful (i.e. needs exposing `.painter.stdout.flush()` in a some way).
Current approach also makes painter a bit stateful and works just because `self.paint()` is called right after `print_external_message` …

Remove flicker on external print

---

src/edit_mode/emacs.rs
src/engine.rs
src/enums.rs

* `Submit` is used to return data unconditionally. This is useful for example if you want compiler to show you where the unclosed paren that doesn't pass validation actually is.
* `SubmitOrNewline` is similar to `Enter` but inserts a new line if the cursor is not at the end of the buffer. It's useful to insert newlines in the middle of the text when editing.
This also removes unconditional `KeyCode::Enter` to `ReedlineEvent::Enter` event mapping and sets it in the keybindings normally (so you can rebind to `Submit` or `SubmitOrNewline`)

Add `Submit` and `SubmitOrNewline` editor events

---

README.md
src/lib.rs

The first two README examples became rotten and were out of sync with
the doctested version from the `lib.rs`

Fix examples in README based on lib.rs

---

src/painting/painter.rs
src/painting/prompt_lines.rs
src/prompt/base.rs

This PR makes nushell+starship behave like other shells (e.g. zsh).
Related: starship/starship#3982 
Closes nushell/nushell#4909
* nushell native prompt
* nushell + starship(disable `line_break` and `add_newline`)
* nushell + starship(enable `line_break` and disable `add_newline`)
* nushell + starship(enable `line_break` and `add_newline`)

render right prompt on the last line of the left prompt

---

src/engine.rs
src/painting/painter.rs

Modal editors such as vim/neovim/etc. often use different cursors for different edit modes.
In it's current state, this pr changes the cursor to a line if the user is in insert mode, and uses a block cursor for all other modes (including custom and emacs). 
Unfortunately, there is no way to retrieve the current cursor shape in crossterm that I know of, so restoring the previous cursor when exiting reedline could prove to be quite difficult. I currently can think of two solutions for this:
1. Use the block or a configurable cursor as "standard" and set that whenever reedline exits
2. Somehow retrieve the cursor upon starting reedline. This could also be quite useful as it would allow to use that as the default cursor for modes which don't need an indicator, I'm specifically thinking of …

change cursor shape depending on edit mode

---

src/core_editor/editor.rs
src/engine.rs
src/enums.rs
src/main.rs

This PR makes nushell tab completion behave more like zsh/bash. Assuming `quick_completions = true`:
- Changes Tab so that it completes instead of selecting the next menu item (arrow keys can be used for that)
- Completion is "as far as possible". So, the entire word if there's a unique completion, or else up to the shared prefix of possible completions.
- Gets rid of the quick completion behavior whereby a word was completed automatically as soon as the input came to have a unique completion.
See https://github.com/nushell/nushell/pull/6802 to use this with nushell.

Tab inline completion

---

src/painting/painter.rs

When enable last line mode, the right prompt may be rendered incorrectly if we have multiline input or hint.
This PR makes right prompt show on the indicator line when last line mode enabled.
* before
* after

show right prompt on indicator line in last line mode

---

src/history/base.rs
src/history/cursor.rs
src/history/mod.rs
src/lib.rs
src/main.rs
src/result.rs

Follow-up on https://github.com/nushell/reedline/pull/474
7d721a1 introduced the sqlite-dynlib feature, but using it in places
where sqlite is currently used was not possible, because the cfg gates
weren't adjusted yet. This commit replaces each `feature = "sqlite"`
with `any(feature = "sqlite",feature = "sqlite-dynlib")`, meaning that
it doesn't matter which sqlite feature you use, reedline will expose the
same API.

fix: actually use sqlite-dynlib feature

---

.github/workflows/ci.yml

Alternative to #503
Using `actions-rust-lang` instead of `actions-rs` for setup. (nushell uses them for setup with integrated caching)
Remove build stage as this should also be covered by test.
clippy --all to see if this checks the examples as well.

Update workflow to new actions (alternative)

---

Cargo.toml
examples/demo.rs
examples/event_listener.rs
examples/list_bindings.rs

Separate fully featured demo from keybinding listing and event listener
Allows to make `gethostname` dev-dependency
What was previously accessible through flags on `cargo run` now becomes:
```
cargo run --example demo
```
```
cargo run --example demo -- --vi
```
```
cargo run --example event_listener
```
```
cargo run --example list_bindings
```

Split the main example binary into examples

---

src/edit_mode/vi/motion.rs
src/edit_mode/vi/parser.rs
src/engine.rs

Fixes nushell/nushell#6991
Allows using `l` to complete the history hint in normal mode
Support menu navigation with `hjkl` in vi normal mode
Adjusts tests

Fix the additional moves of normal mode `hjkl`

---

examples/custom_prompt.rs
examples/validator.rs
src/painting/painter.rs

I made a small example how to implement a custom validator and a custom prompt.
I'm not sure if this is the right way to do it, but the example works as I anticipated.
One option is to merge as is, or rename it to `validator_prompt` (is it kind of covers both), or alternatively split them in two (as they are kind of independent).
Let me know what you think is best way forward.

Custom validator and prompt code examples

---

src/engine.rs

Is considered a potential optimization:
https://nnethercote.github.io/perf-book/standard-library-types.html#box

Use `Box::default()` in more places

---

examples/demo.rs
src/lib.rs
src/prompt/default.rs
src/prompt/mod.rs

I was working on a small REPL application, and I found that the default prompt was a bit overkill (and more suited for a shell).
So, I made the `DefaultPrompt` struct more configurable, so you can do things like this:
```rust
let prompt = DefaultPrompt {
left_prompt: DefaultPromptSegment::Basic("rand-api".to_owned()),
right_prompt: DefaultPromptSegment::Empty
};
// or
let prompt = DefaultPrompt::new(
DefaultPromptSegment::Basic("rand-api".to_owned()),
DefaultPromptSegment::Empty
);
```
with a result like this:
I modified `DefaultPrompt::default()` to produce the same behavior as before. So, users who were using `DefaultPrompt::default()` (as per the example in the readme) should in theory see no breaking changes.
I.e., the following
```rust
let prompt = DefaultPrompt::default()
```
will …

Make DefaultPrompt configurable

---

examples/demo.rs
src/edit_mode/cursors.rs
src/edit_mode/mod.rs
src/engine.rs
src/lib.rs
src/painting/painter.rs
src/prompt/base.rs

This pr is a follow-up to #494. There were various complaints about my implementation being to invasive, so for now I made it toggleable, but I would like not only be able to toggle this, but to actually make it configurable.
If merged, this should resolve #514.

Make reedline handling cursor shapes more configurable

---

examples/basic.rs
examples/completions.rs
examples/custom_prompt.rs
examples/demo.rs
examples/event_listener.rs
examples/external_printer.rs
examples/highlighter.rs
examples/hinter.rs
examples/history.rs
examples/list_bindings.rs
examples/validator.rs
src/completion/base.rs
src/completion/default.rs
src/engine.rs
src/history/cursor.rs
src/history/file_backed.rs
src/history/sqlite_backed.rs
src/menu/list_menu.rs
src/painting/styled_text.rs
src/prompt/base.rs
src/prompt/default.rs
src/utils/query.rs

The color of the multiline prompt is currently hard-coded to be `LightBlue`. This ended up being a pretty straightforward change to allow it to be configured using the `Prompt` trait similar to the other prompt colors.
One oddity in here is that the multiline prompt uses a `nu_ansi_term::Color`, whereas the other colors use a `crossterm::style::Color`. I'm not sure which one is preferred at this point, but I'd be willing to work toward some consistency if there's a current direction toward one or the other.

Allow configuration of multiline prompt color

---

src/lib.rs

`rustdoc::missing_doc_code_examples` apparently only works on nightly and causes unnecessary warnings appearing in the CI output.

Remove unstable rustdoc lint

---

Cargo.lock
Cargo.toml

Necessary for the `0.75` nushell release

Bump version for `0.15` release

---

src/history/base.rs
src/history/file_backed.rs
src/history/sqlite_backed.rs
src/result.rs

Adds a `History::clear()` function that deletes all history items. Closes #535.
Will eventually close https://github.com/nushell/nushell/issues/7991

Add History::clear() function

---

src/history/sqlite_backed.rs

Quick follow-up to #535: we should run [`VACUUM`](https://www.sqlite.org/lang_vacuum.html) after clearing the `history` table, to ensure that history is fully erased. Without a `VACUUM`, history may be recoverable by looking at the raw database files.

VACUUM after deleting SQLite data

---

Cargo.lock
Cargo.toml

Expected to contain minor bugfix and work on `History::clear` API (work
to improve history metadata handling still in progress)

Bump version for `0.16.0` release.

---

src/engine.rs

relevant: https://github.com/nushell/nushell/pull/8105
allows ctrl+o keybinding to take command arguments into account

allow reedline ctrl+o to take editor arguments

---

.gitignore
Cargo.toml

I validated it with the cli `cargo msrv`:
```
cargo msrv
[Meta]   cargo-msrv 0.16.0-beta.8 (a1b5066)                                                                                                                                                                                                                                                                       
Compatibility Check #1: Rust 1.62.1
[OK]     Is compatible 
Compatibility Check #2: Rust 1.59.0                                                                                                                                                                                                                                                                                   [FAIL]   Is incompatible …
```

Set MSRV to 1.62.1

---

src/menu/menu_functions.rs

This is an attempt to fix https://github.com/nushell/nushell/issues/8412.
I believe that the issue is caused because of the reference to reedline.  
I believe that if we implement this fix, bump the version and use the new version inside nushell, then the bug should be resolved.  
This is my first PR in Rust so happy to change anything you see as an issue!

Allow multi byte characters as the marker without panicking

---

Cargo.lock
Cargo.toml

Bump version for `0.18.0` release

---

src/lib.rs

Some default Prompt methods require crossterm::Color for manual implementation (`get_prompt_color` for example).  This re-exports Color for use by custom Prompt implementers.

re-export crossterm::style::Color for custom prompt implementations

---

src/engine.rs

For [fix: set the initial repl cursor pos, fixes #8943 by stevenxxiu · Pull Request #8955 · nushell/nushell](https://github.com/nushell/nushell/pull/8955).

feat: add `current_insertion_point()` to return the current insertion point of the input buffer

---

src/edit_mode/emacs.rs
src/edit_mode/vi/mod.rs

Fixes: #576
Actually the issue comes from iterm2 setting when I want to paste multiline script:
But yeah, when we enable bracketed paste, we can avoid pasted script to be executed automatically, I think it's safe to transfer from `\r` to `\n`. 
Currently I'm not sure how windows handle bracketed feature, since it doesn't work with crossterm lib, I'm going to convert from "\r\n" to "\n" to make sure that everything is working properly

fix bracketed paste

---

src/edit_mode/emacs.rs
src/edit_mode/vi/mod.rs

Nushell exposes `control_alt` and similar keybinding modifiers, but currently it's not possible to actually use those mappings in nushell (at least on none of my keyboards).
From some limited testing, it appears like GNU readline also doesn't allow mapping `CTRL+ALT+f` and similar keybinds. I don't know if there's some deeper reason behind this, or just a limitation of readline itself. I can't think of any edgecases my change would break, since it's only if you actively choose to add a binding.
I use those keybinds quite extensively in other shells, so it'd be nice to have in nu as well.
Combinations like `Ctrl+Alt+a` could not be mapped previously, since some non-us keyboard layouts use those combinations for sending characters like `@`.
Now, first check if there a binding was defined …

Allow binding of CTRL+ALT+<c>, SHIFT+<c> and CTRL+ALT+SHIFT+<c>

---

src/painting/painter.rs

Fix: https://github.com/nushell/nushell/issues/9015
Previously, when the terminal window shrinks its height, the prompt eats the previous line.
Now, the prompt will not overwrite the previous line.

fix: prompt position on resize

---

examples/external_printer.rs
src/engine.rs

Currently if a sent string doesn't contain \r, it just prints on a new line without the carriage return:
This is the expected output:
This fixes that by always splitting the received line into lines.  The example is updated to demonstrate.

Update to make work with new lines embedded in sent string.

---

Cargo.toml

Reincludes the patch versions that were removed in #586 to ensure
reedline gets built with a version with which we tested reedline at some
point.

Revert removal of patch versions

---

Cargo.lock
Cargo.toml

~Intended for nushell `0.80`~
**Update:** will not ship with 0.80 due to insufficient real world testing.
See the concerns around the features in https://github.com/nushell/nushell/pull/9207

Bump to `0.20.0` for release

---

src/engine.rs
src/enums.rs

Want to add `disable_bracketed_paste` method for reedline engine, hope it can make nushell works with `bracketed_paste` better.
Relative issue: https://github.com/nushell/nushell/issues/9218
I think paste password inside `gpg` should work fine even when `bracketed_paste` is enabled.
To fix the issue, we can have something like a `DisableBracketedPaste` guard during nushell repl.  But it requires reedline to provide this funciton.

add a new disable_bracketed_paste method

---

Cargo.lock
Cargo.toml

Bump version for `0.21.0` release

---

src/engine.rs

According to @sholderbach 's comment: https://github.com/nushell/nushell/pull/9399#issuecomment-1585692641
It's good to disable bracketed paste in reedline rather than nushell

always disable bracketed paste after read_line

---

Cargo.lock
Cargo.toml

`cargo audit` reported a potential segfault in the time crate, this PR adopts the proposed change in https://rustsec.org/advisories/RUSTSEC-2020-0071.
```
Crate:     time
Version:   0.1.45
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Severity:  6.2 (medium)
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.45
└── chrono 0.4.24
└── reedline 0.21.0
```

Remove unneeded features of chrono

---

Cargo.lock
Cargo.toml

- `strum`/`strum_macros` enables upgrade to `syn 2.0`
- `pretty-assertions` gets rid of `ctor` and other outdated dev-deps
- `rstest` also helps with `syn` but introduces `regex` dev-dep

Update (dev-)deps strum/pretty-assertions,rstest

---

Cargo.lock

We didn't update in a while.
Since then some transitive dependencies have been replaced.

Update the `Cargo.lock` for tests and demo

---

Cargo.lock
Cargo.toml

Side effect we don't duplicate `windows-sys` anymore
Wait to land on sharkdp/lscolors#72 as `nu` has to interact with both `reedline` and `lscolors` via `nu-ansi-term`.

Bump `nu-ansi-term` to 0.49.0

---

src/painting/painter.rs

Before this PR, the bold attribute was hard coded and therefore leaked through. Example:
Notice that the prompt is green bold even though I told it just green. Also, when i draw the prompt with the `do` command, it's drawn right. This is because the `do` command is rendering a buffer and the PROMPT_COMMAND is going through this code in reedline and hard-coding bold everywhere.
Notice that when i tell it green, the prompt is drawn in green and with the `do` command. When I tell it green_bold the prompt is drawn in green_bold as well as with the `do` command.
This is meant to close https://github.com/nushell/nushell/issues/9123 when it's implemented in nushell.

turn off default prompt styling (bold) to prevent leakage

---

Cargo.lock
Cargo.toml
src/painting/utils.rs

This PR updates `strip-ansi-escapes` to their latest api changes. Apparently, `strip_ansi()` cannot fail now?
Closes #616

update `strip-ansi-escapes` to their latest api

---

Cargo.lock
Cargo.toml

This PR updates strip-ansi-escapes to 0.2.0. Hopefully this will fix these problems once and for all.

update to strip-ansi-escapes 0.2.0

---

src/engine.rs

Supporting Kitty keyboard enhancement protocol to enable vi action on other keyboard layout (e.g. ctrl+i on Colemak). Without this, ctrl+i will equivalent to Tab and cannot be remapped to anything else.
Add config `use_kitty_protocol` to determine whether to enable kitty protocol or not. Then if the terminal support this, send the request to enable this terminal feature. Also disable it back when ~the engine dropped~ the event handler finished.

Add Kitty protocol keyboard enhancement support

---

src/engine.rs

The result type is not `crossterm::Result` (anymore), but `std::io::Result`

Fix `read_line` docs

---

examples/custom_prompt.rs
examples/transient_prompt.rs
src/engine.rs
src/prompt/base.rs

This PR goes towards addressing #348. It adds `fn repaint_on_enter(&self) -> bool` to the `Prompt` trait so that a prompt can choose to be repainted on enter. I figured an option could be added to `$env.config` on the Nushell side to enable a transient prompt. After that, the hooks described in [this issue](https://github.com/nushell/nushell/issues/7843) will hopefully start working.

Let prompts choose to repaint on enter

---

.github/workflows/ci.yml

Let's try to use it, mostly for observing how our internals are tested. 
The UI side of things is poorly covered and will require some extra work to be testable end-to-end. (`cargo-llvm-cov` setup would probably also need to change)

Setup coverage with codecov.io

---

.github/codecov.yml
README.md

For the file took most of the settings we used for nushell/nushell
Adjusted the warning threshold (not sure how we should set it up in practice, yet)

Add a configuration to codecov.io

---

examples/demo.rs
src/history/base.rs
src/history/sqlite_backed.rs

After this change (with enabled history isolation), we will get rows:
- that have the same session_id, or
- have a lower id than the first command with our session_id, or
- if there's no command with our session_id, take the whole history.
See https://github.com/nushell/nushell/issues/10104#issuecomment-1693632190 for an example of the new behavior

Improve history isolation

---

README.md

This should reflect that we do not strive to be a one-for-one `readline` replacement and have our own opinionated choices.

Update motto title

---

examples/demo.rs
src/engine.rs

Thin pr contains the reedline-side change for  https://github.com/nushell/nushell/pull/10210
`BufferEditor` in current reedline only use a big string to represent editor and it's arguments, which is broken when editor's path contains any spaces. This pr make `BufferEditor` also accept `list<string>` from `$nu.EDITOR` just like `config env`.
(To avoid breaking current version of nushell, this pr add a new api `with_argumented_buffer_editor` instead of directly modify `with_buffer_editor`.)

Accept `Command` with args for `BufferEditor`

---

src/menu/list_menu.rs

https://rust-lang.github.io/rust-clippy/master/index.html#/format_collect

Fix clippy lint from most recent Rust

---

examples/cwd_aware_hinter.rs
src/hinter/cwd_aware.rs
src/hinter/default.rs
src/hinter/mod.rs
src/history/base.rs
src/lib.rs

towards https://github.com/nushell/nushell/issues/8883

add cwd aware hinter

---

src/engine.rs

When reading input, start by calling `event::read`, which efficiently blocks until input arrives, rather than polling for input every 100 milliseconds.
This preserves the existing `POLL_WAIT` polling behavior by moving the poll after the first `read` call returns.
Fixes #521.

Avoid consuming CPU when waiting for input.

---

src/hinter/cwd_aware.rs
src/hinter/default.rs
src/hinter/mod.rs

Partial completion behaves now like usual word movements by C-Left and C-Right.
This is also useful to accept only parts of a suggested path.

Split hinter tokens at Unicode word boundaries

---

Cargo.toml
examples/cwd_aware_hinter.rs
examples/external_printer.rs

This PR forces examples that need certain features to nag about needing those features and not compile without specifying them.

don't allow certain examples to compile without their features

---

src/engine.rs

Due to a supposed issue (https://github.com/nushell/nushell/issues/9218) in nushell regarding commands that read standard input, a fix (https://github.com/nushell/nushell/pull/9399) was proposed that temporarily disables bracketed_paste during the execution of [eval_source](https://github.com/WindSoilder/nushell/blob/cf7040a215fa8d4008844f7fefc2abacc7482546/crates/nu-cli/src/util.rs#L205-L230). 
Instead, this issue was moved over to reedline and a new PR was created (https://github.com/nushell/reedline/pull/598). In this version of the "fix", bracketed_paste is disabled completely after the first execution of reedline. This has led to issue https://github.com/nushell/reedline/issues/648, where multiline paste is now being disabled on non-windows environments.
This PR effectively reverts …

re-enable bracketed paste on not(windows) (fixes #9944) (fixes #648)

---

src/lib.rs
src/result.rs

Allows implementing custom `History` types
Closes #545

Make `Result` and `ReedlineError` public

---

src/history/item.rs

As the item's documentation indicates, the history item's internal ID is auto-incremented.
Which means we can use it to order entries, as well as using it as e.g. an `HashMap`s key.

Add more derive impl for HistoryItemId

---

src/hinter/cwd_aware.rs

closes https://github.com/nushell/nushell/issues/10921

CwdAwareHinter: remove cwd filter when there are no results

---

.github/workflows/ci.yml
examples/cwd_aware_hinter.rs
examples/transient_prompt.rs

This PR also fixes existing clippy lints

Also run clippy on examples

---

examples/demo.rs
src/engine.rs
src/lib.rs
src/terminal_extensions/bracketed_paste.rs
src/terminal_extensions/kitty.rs
src/terminal_extensions/mod.rs

Both bracketed paste and the kitty keyboard enhancement flag are not always supported.
This goes both for terminals that may not emit events according to the extensions thus we already provide the means to only optionally enable them.
But also the applications that may run between each `Reedline::read_line` call are in no way guaranteed to supported any enhanced terminal events coming in.
It should thus be part of reedline's contract to leave `read_line` in a clean state with the canonical terminal behavior.
The API for `Reedline::enable_bracketed_paste` was misleading as it for the most part acted independent of the `Reedline` state and immediately globally enabled bracketed paste, potentially polluting any application during evaluation. `disable_bracketed_paste` equally globally …

Properly handle optional event modes

---

Cargo.toml

Inspired by https://github.com/nushell/nushell/pull/11180
Make sure you can see all available types/symbols on docs.rs
(e.g. `SqliteBackedHistory`)
In a second step we should take care of annotating feature gated stuff
correctly

Build docs.rs docs with all features

---

src/result.rs

This PR allows to build a custom `History`, which requires returning `Reedline<_, ReedlineError>` values ; the problem being that `ReedlineError` values aren't currently constructable from outside of the `reedline` crate itself.
This will require to carefully craft the variants once we decide to publish the 1.0 version

Allow to construct ReedlineError values from the outside

---

src/history/item.rs

This PR allows to restore `HistoryItemId` values (and so `HistoryItem` as well) from e.g. a custom serialized history.
Required to implement a custom `History`.

Allow to build HistoryItemId values from the outside

---

src/edit_mode/vi/command.rs

make `cw`/`cW` delete uptil the next space (like `ce`/`cE`). See [the vim help page on `cw`](https://vimhelp.org/change.txt.html#cw). This behavior is in both `zsh` and `bash`

vi mode: map `cw`/`cW` to `ce`/`cE` by default

---

Cargo.lock
Cargo.toml

This patch release is purely intended to fix the docs.rs build fail

Bump version to 0.27.1

---

src/painting/painter.rs
src/painting/prompt_lines.rs

There are still some edge cases I plan to continue to work on, but I have changed the behaviour so that when a resize happens, the editor queries the position. Otherwise it's very hard to know if there is some data above the screen throwing off the calculated offsets or potentially weird control characters messing with the offset.
My plan is to:
- test on more terminals
- figure out why on some terminals, there are some oddities after a CMD-K refresh
- dogfood it a bit to see if I find any other edge cases

Better behaviour on resize

---

src/painting/painter.rs

Try to fix nushell/nushell#11399

Fix `prompt_start_row` reset to 0 when opening a file without newline in Nushell

---

Cargo.lock
Cargo.toml

Most recent version of itertools.
Used by nushell crates.
Several crates in the ecosystem are still working with `0.11.0`

Bump `itertools` to `0.12.0` from `0.10.x`

---

src/hinter/cwd_aware.rs
src/hinter/default.rs

Fix clippy from the future

---

.typos.toml
src/painting/painter.rs

This pr is going to apply one of solution that @nibon7 attempted: https://github.com/nushell/nushell/issues/11399#issuecomment-1867921387
Relative: https://github.com/nushell/nushell/issues/11399

Try fix prompt_start_row reset to 0 when opening a file without newline in Nushell 

---

src/lib.rs
src/result.rs

Following #676, this PR makes `ReedlineErrorVariants` public in order to allow constructing it from outside of `reedline`.

Make `ReedlineErrorVariants` public

---

src/engine.rs

Fixes #582 
Reverts part of #97 -- Normal traversal sets history string at cursor to line buffer. It's not clear to me what that was added in response to.
Added tests covering the problem and the fix in `engine.rs`. The bug occurs in `engine.rs`, so it's not possible to test in `core_editor/line_buffer.rs`, where the other edit command tests are.
Completed the UX checklist the best I could, and ran nushell with the fix for a bit.
Relevant features tested (leave open if you did not consider those areas touched by your PR):
Build: [x] debug / [ ] release
Platform:
Terminal emulator:
Inside a [ ] ssh,[ ] tmux or [ ] screen session?

Fix move to line start in multi-line history entries

---

src/painting/painter.rs

Currently, if the buffer is too large to display all at once and you have a completion menu, the text after the cursor isn't displayed. Apparently, it's a difficult problem to show all of the text after the cursor that isn't covered by the menu, but this PR is only for showing the rest of the text on the same line as the cursor.
This is the current behavior. You can't tell which keys I'm pressing in the video, but when I type `foo`, then place my cursor before `foo` and hit tab to activate the completion menu, the `foo` disappears while my cursor is before it. If you move the cursor one word ahead, you'll see the `foo` again (my recording doesn't actually show this, I'll make a new one later when I'm not feeling so lazy but you should be able to reproduce on your own computer). …

Print rest of line after cursor with large completion menu

---

examples/completions.rs
src/completion/base.rs
src/completion/default.rs
src/completion/history.rs
src/engine.rs
src/menu/columnar_menu.rs
src/menu/list_menu.rs
src/menu/menu_functions.rs

Goes towards fixing https://github.com/nushell/nushell/issues/8091. https://github.com/nushell/nushell/pull/11488 (which should finish the job) relies on this PR to make `only_buffer_difference: true` work with the columnar and list menus.
I don't know what exactly the old behavior was supposed to be (I looked at the history of the relevant files but couldn't find any recent commits that seemed to change behavior), so maybe this PR has different behavior for the user (it also changes the contract of `Completer::complete`). But I think I've narrowed down the issue, so someone else can at least make a new PR based on that.
It seems like the problem was in `DefaultCompleter::complete`, where it does `line[0..pos]`:
https://github.com/nushell/reedline/blob/f3962232bad6124f41a3725d026468615e31a …

Don't slice line in DefaultCompleter

---

src/engine.rs

Reverts nushell/reedline#584
This is causing odd test behavior like ansi escapes, seeing reedline prompts in the middle of testing, leaving the terminal in a raw state.
@boathouse2112 If you can find a fix for this it would be great!!
These are the two test commands that I run and see the problems.
```
cargo test --features=bashisms,sqlite,external_printer,system_clipboard
```
and
```
cargo nextest run --all-features
```

Revert "Fix move to line start in multi-line history entries"

---

Cargo.lock
Cargo.toml
src/core_editor/clip_buffer.rs

Adresses #606 and [this request](https://github.com/nushell/nushell/pull/11535#issuecomment-1890960094)
Replace `clipboard` dependency with [arboard](https://crates.io/crates/arboard). 
A look at crates.io shows that there are currently two major cross-platform clipboard crates to choose from:
1. [arboard](https://crates.io/crates/arboard)
2. [copypasta](https://crates.io/crates/copypasta)
`copypasta` is maintained by the `alacritty` project, which gives some confidence in the future maintenance story. Using this crate as a drop-in replacement for `clipboard` works just from an API standpoint, but leads to failure of `cargo test --features system_clipboard core_editor::clip_buffer::tests::reads_back` on windows. This is due [this bug](https://github.com/DoumanAsh/clipboard-win/pull/23) …

Replace clipboard with arboard, which is actively maintained

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/motion.rs
src/edit_mode/vi/parser.rs
src/edit_mode/vi/vi_keybindings.rs
src/engine.rs
src/enums.rs
src/painting/styled_text.rs

Addresses issue #380.
> All CutXXX commands like "CutFromStart" or "CutWordLeft" should use the OS copy/paste buffer not an internal buffer
This is already the case if the crate is compiled with the feature `system_clipboard`. This is, afaik, not (yet) done for nushell.

Add ability to select and cut text in the input buffer

---

src/lib.rs
src/menu/columnar_menu.rs
src/menu/ide_menu.rs
src/menu/mod.rs
src/painting/prompt_lines.rs

get correct cursor pos when menu indicator contains newline

---

src/history/base.rs
src/history/file_backed.rs

As of now, setting `capacity` to 0 causes a panic, defaulting to 1 solves this issue with minimum overhead.
Fixed issue: nushell/nushell#10826

Fix panic when history size set to 0

---

src/edit_mode/keybindings.rs

Fixes issue https://github.com/nushell/nushell/issues/11600
The issue was that Ctrl+C was bound to copy the selected test after the already existing CtrlC command.

Remove conflicting keybindings added with selection feature

---

src/core_editor/clip_buffer.rs
src/core_editor/editor.rs

If the `system_clipboard` feature is enabled, gracefully handle the case where the system clipboard can't be accessed and default to `LocalClipboard` in that case instead of panicking. This should help with running nu scripts in a docker container for instance.

Clipboard graceful handling

---

src/completion/base.rs
src/completion/default.rs
src/completion/history.rs
src/menu/columnar_menu.rs
src/menu/ide_menu.rs
src/menu/menu_functions.rs

Reverse highlighting with config "record" for reverse:
```nushell
style: {
text: white
selected_text: {
attr: r
}
description_text: white_dimmed
}
```
related https://github.com/nushell/nushell/issues/5292
related https://github.com/rsteube/carapace/pull/546

suggestion: added style

---

examples/demo.rs
src/history/base.rs
src/history/file_backed.rs
src/result.rs

This pr makes `FileBackedHistory::new()` return `Result<FileBackedHistory>` and it will not panic when passing `usize::MAX` as capacity.
When setting `$env.config.history.max_size = -1`,  nushell returns an error instead of panicking.
```console
❯ ./target/debug/nu
Error:   × error within history: History capacity too large to be addressed safely
```

 Don't panic when creating `FileBackedHistory` with `usize::MAX` capacity 

---

src/result.rs

This makes the history error message much clearer that it is coming from *Reedline*...
Since Reedline is used by many different applications where the end user does not
even know that Reedline is used in the product it gives a better hint to both the developers
of Reedline who are embedding Reedline in their application and the end user who is reporting
back to someone what error message they are seeing...

update history error message

---

src/painting/painter.rs

Fixes #727
Previously, when printing large buffers, the foreground color for the prompt indicator and right prompt wasn't printed.
Below is the original behavior. You can see that with a small buffer that doesn't fill up the whole screen, the menu indicator (`|`) is blue and the right prompt is purple, as expected. But with a large buffer, both become green.
[![asciicast](https://asciinema.org/a/D9bu9pnpHYziMyUsrAe8Azmoz.svg)](https://asciinema.org/a/D9bu9pnpHYziMyUsrAe8Azmoz)
Below is the new behavior. The menu marker and right prompt are the expected colors even with a large buffer.
[![asciicast](https://asciinema.org/a/RHfh4dfkZttJ3VTAHekk69KND.svg)](https://asciinema.org/a/RHfh4dfkZttJ3VTAHekk69KND)

Print foreground color for indicator and right prompt in large buffers

---

examples/completions.rs
src/menu/columnar_menu.rs
src/menu/ide_menu.rs
src/menu/mod.rs

closes #724
Adds ``selected_match_style`` and ``match_style`` to ``MenuTextStyle``.
IdeMenu
ColumnarMenu

Typed text style

---

src/engine.rs

Fix quick completion

---

src/edit_mode/vi/mod.rs

As mentioned in #694 using the `vi` editor mode does not match the behavior of the `vim/vi` CLI editors.

Move left when exiting insert mode

---

Cargo.lock
Cargo.toml

Built and tested nushell with this version of rusqlite & reedline as well.

Bump rusqlite from 0.29.0 to 0.31.0

---

src/engine.rs

Fix rendering prompt after ExecuteHostCommand

---

Cargo.lock

Motivated by advisory for transitive dependency `mio`
https://rustsec.org/advisories/RUSTSEC-2024-0019.html
This does not have a direct effect on library users.

Bump dependencies in lockfile

---

Cargo.lock
Cargo.toml

Most recent minor version: 0.26
Should be the same as nushell to reduce dependency duplication

Bump version of `strum`/`strum_macros`

---

src/core_editor/clip_buffer.rs
src/core_editor/editor.rs
src/core_editor/mod.rs
src/edit_mode/keybindings.rs
src/enums.rs

This PR addresses https://github.com/nushell/reedline/issues/759. 
This PR reverts most commands to using the local cut buffer for cut/copy/paste operations except for `CutSelection` and `CopySelection`. Those two commands now have a parameter to specify which clipboard to use. Current keybindings for those commands (`CutSelection`: `Ctrl+Shift+X`, `CopySelection`: `Ctrl+Shift+V`) still use the system clipboard. Currently, no keybindings are defaulted for these commands and the cut buffer. 
We can't statically compile everything related to the `system_clipboard` feature out, as that would include the parametrized commands mentioned above. Activating the feature would not be purely additive anymore. Therefore those parameters have to stay even when the feature is disabled and the commands …

Use the OS clipboard only for explicit cut/copy/paste operations

---

src/history/file_backed.rs

`truncate(false)` is the right choice as we manually truncate later. (we
want to read from the same handle first and then write, to use the
advisory lock)

Fix `OpenOptions` clippy

---

src/history/base.rs
src/history/sqlite_backed.rs

After merging downstream will close https://github.com/nushell/nushell/issues/10131
For the `FileBackedHistory` those operations have always been case
sensitive, do the same for `SqliteBackedHistory`. The insensitivity of
`like` in sqlite causes https://github.com/nushell/nushell/issues/10131
Replace this with exact matching via sqlite's [`instr()`](https://www.sqlite.org/lang_corefunc.html#instr), which should also fix a need for escaping of `%` (or `*` with `glob`)

Fix case-consistency searching sqlite history

---

examples/ide_completions.rs
src/menu/ide_menu.rs

fix ide menu not reporting correct required_lines

---

src/engine.rs
src/painting/mod.rs
src/painting/painter.rs

First PR for nushell/reedline \o/
Revert/Rewrites #758
Fixes #755 (correctly this time 😬)
<details>
<summary>Where did the newline actually come from in that issue?</summary>
The _phantom_ newline that OP reported was due to this block in painter initialization:
(👉 It would detect some text before the cursor and always make a new prompt on the next line..)
https://github.com/nushell/reedline/blob/0698712701418a7212ebf75d5724d72eccc4b43f/src/painting/painter.rs#L107-L120
</details>
Fixes #771 (my issue)
Now I have the same experience than on my zsh config :smiley: 
Supports everything I mentioned in #771
Supports replacing the prompt (even from multi-line old prompt)
https://github.com/nushell/reedline/assets/9730330/ab52e593-cc1d-4762-8df8-9e5774538531
---
What do you think of this …

Fix (properly) the logic around prompt re-use & Host Command handling

---

src/engine.rs
src/hinter/cwd_aware.rs
src/hinter/default.rs
src/hinter/mod.rs
src/history/base.rs

This PR adds the current working directory as part of the `Reedline` state, instead of using `std::env::current_dir()` to retrieve it from the environment. Applications should call `Reedline::with_cwd()` to update the current working directory when it changes.
This is necessary to support https://github.com/nushell/nushell/pull/12922, which causes `std::env::current_dir()` to deviate from Nushell's `$env.PWD`.

Add PWD to the `Reedline` state

---

src/edit_mode/emacs.rs

When making relative pr in nushell: https://github.com/nushell/nushell/pull/13801
I found it would be good to change the keybinding here too.
This pr is going to change ctrl-k to `cut to line end`, rather than `cut to end`.

emacs mode: change ctrl-k to `cut to line end`

---

src/engine.rs

This PR is meant to address a nushell specific issue (https://github.com/nushell/nushell/issues/11251) about the tab button not partially completing suggestions if the menu is already open. I added partial completions to the MenuNext event after checking if they were enabled.

Added partial completions to the MenuNext event

---

examples/demo.rs

Rel: #834 Added MenuNext as a menu event upon pressing tab to the demo example. Fixes the currently broken completions on the example.

Fixed demo completions

---

src/engine.rs
src/menu/menu_functions.rs

Addresses #833 . `menu.can_partially_complete()` would reset the current selection 0 and return true even if the suggested partial completion was exactly the same. Changed `can_partially_complete` in `menu_functions` to return false and not complete if the suggested partial completion is the exact same as the input.

made can_partially_complete() only complete when suggesting more than the input

---

src/edit_mode/emacs.rs
src/edit_mode/vi/mod.rs
src/engine.rs
src/enums.rs

This PR makes it so that Reedline no longer wait for `POLL_WAIT` after every keystroke. Instead, the delay is only triggered if text pasting or resizing is detected.
It also re-introduces a fix from PR #651. That PR was reverted by #840 because of issue #757 about external printers. If the feature `external_printer` is not enabled, this PR will just block on input forever for maximum power efficiency. Users with `external_printer` enabled will also see a small improvment in power efficiency, because this PR makes it possible to use a longer polling inteval without affacting typing latency.
Fixes #643, [#10484](https://github.com/nushell/nushell/issues/10484), and #521, and hopeful doesn't break #757.

Reduce typing latency caused by `POLL_WAIT`

---

src/menu/columnar_menu.rs

Fixes #837.
https://github.com/nushell/reedline/blob/4634f71705785a772c894aa45e30db88f3c7a8d5/src/menu/columnar_menu.rs#L305
[split_at](https://doc.rust-lang.org/std/string/struct.String.html#method.split_at ) expect byte offset.
https://github.com/nushell/reedline/blob/4634f71705785a772c894aa45e30db88f3c7a8d5/src/menu/columnar_menu.rs#L302
But we given (got from [width](https://docs.rs/unicode-width/latest/unicode_width/trait.UnicodeWidthStr.html#tymethod.width)) isn't.
Thanks for all amazing works in reedline.

Fix wrong unit when split string

---

.github/workflows/ci.yml
.github/workflows/typos.yml
Cargo.lock

Wasn't commited with the last release or similar.
Added the CI step we have on the main repo to catch leaky tests or uncommited lockfiles

Fix forgotten `Cargo.lock`

---

src/edit_mode/keybindings.rs

Implements #792 and also should be the proper implementation of https://github.com/nushell/nushell/pull/13606
---
Adds <kbd>Alt</kbd>+<kbd>Enter</kbd> and <kbd>Shift</kbd>+<kbd>Enter</kbd> as keybindings to insert a newline in Emacs and Vi-insert modes.
In the Nushell PR, @sholderbach said:
> so it might be that for some `Alt-Enter` won't work while for others `Shift-Enter` or `Ctrl-Enter` is unreliable.
I figure there's no reason we can't just bind *both* so that multiple platforms and terminals can handle this gracefully.  I know <kbd>Alt</kbd>+<kbd>Enter</kbd> is commonly captured by Windows Terminal, and <kbd>Shift</kbd>+<kbd>Enter</kbd> doesn't seem to be recognized on Linux (also via `input listen`).
If the Terminal captures one of the keybindings, then hopefully the other is …

Add Newline keybindings

---

src/edit_mode/keybindings.rs

Permits terminal automation sending a `\n` to behave the same as if a
`\r` is sent which is the canonical Enter according to ANSI/crossterm
Closes https://github.com/nushell/nushell/issues/6427
See also #832

Set `Ctrl-J`/`\n` to `ReedlineCommand::Enter`

---

src/engine.rs

I'm not quite sure if this is the right approach, but this seems to partially fix the issue in ghostty reported in #684. Unfortunately, this still briefly shows a blank prompt while resizing, but eventually settles to a redrawn prompt

Redraw on resize

---

src/completion/history.rs
src/history/base.rs

- **Remove dead docstring**
- **Elide unused named lifetimes**

Fix clippy lints

---

src/history/file_backed.rs

Fix new clippy lint from 1.84.0

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/mod.rs
src/edit_mode/vi/parser.rs
src/engine.rs
src/enums.rs

This PR addresses several inconsistencies in Reedline's Vi mode implementation, particularly around visual mode and cut operations, making the behavior more aligned with standard Vim.
- Added proper selection clearing when pressing Esc
- Fixed by adding explicit cursor movements to reset selection state
- Ensures visual feedback matches mode state
- Fixed `x`, `s`, `d`, and `c` commands to behave consistently with Vim standards
- Made `x` properly cut selection in visual mode instead of just one character
- Fixed `c` to enter insert mode after cutting selection
- Corrected selection range calculation to be inclusive (include the last character)
- Properly restore normal mode after cut operations in visual mode
- Added mode transitions for `DeleteChar` and `DeleteToEnd` commands
- Fixed …

 Improve Visual Mode Selection and Command Consistency

---

src/core_editor/editor.rs
src/edit_mode/vi/command.rs
src/edit_mode/vi/motion.rs
src/edit_mode/vi/parser.rs
src/enums.rs

Implement vi-mode "Yank" (copy):
- Vi Command;
- Editor Command;
- Editor methods;
- Mode changes back to Normal after yank
Note only last commit in this PR should be reviewed as part of this PR as this is on top of:

Implement vi-mode "Yank" (copy):

---

src/core_editor/editor.rs
src/edit_mode/vi/command.rs
src/enums.rs

This PR adds a keybinding to `o` in Vi visual mode, which swaps the cursor and the anchor - see [here](https://vimdoc.sourceforge.net/htmldoc/visual.html#visual-change) for Vim docs explaining this behaviour.

Add Vi `o` command to swap anchor and cursor

---

src/core_editor/editor.rs
src/edit_mode/vi/mod.rs
src/engine.rs
src/enums.rs

After exiting visual mode with Escape, the selection is currently not cleared until another action is performed such as moving the cursor left or right. This PR fixes that, clearing the selection as soon as Escape is pressed to match the behaviour of Vim.

Clear selection when exiting visual mode

---

Cargo.lock
Cargo.toml

`0.13.0` now the most common among nushell dependencies

Bump itertools version

---

src/menu/columnar_menu.rs
src/menu/ide_menu.rs

This is a stopgap for https://github.com/nushell/nushell/issues/12680, https://github.com/nushell/nushell/issues/13951, https://github.com/nushell/nushell/issues/13630, https://github.com/nushell/nushell/issues/15302.
Fuzzy matching will need more care, and I think @ysthakur knows how to fix that.
https://github.com/nushell/nushell/issues/13951 also exposes another bug in `directory_completion`, i.e. not doing quoting, which is handled properly in `file_completion`.

fix: columnar_menu create_string with quoted suggestions

---

Cargo.lock
Cargo.toml

`unicode-width` has to bundle unicode codepoint tables, so it's quite large (1.5MB).  They've recently released the version 0.2, which caused a split in Nushell dependencies between 0.1 and 0.2, doubling the size.
The main breaking change for `unicode-width` is that `\n` is now counted as having width 1 and not 0.  But that shouldn't matter for reedline, since the menus which use it (columnar/IDE/list) work on lines.

Upgrade `unicode-width` to 0.2

---

Cargo.lock
Cargo.toml

See https://github.com/dtolnay/thiserror/releases/tag/2.0.0.

chore: upgrade thiserror to v2

---

src/core_editor/line_buffer.rs

Fixes clippy(version 0.1.86) error:
```
error: called `Iterator::last` on a `DoubleEndedIterator`; this will needlessly iterate the entire iterator
--> src/core_editor/line_buffer.rs:474:14
|
474 |             .last()
|              ^^^^^^ help: try: `next_back()`
```

fix clippy: call `next_back` instead of `last` on `DoubleEndedIterator`

---

src/menu/columnar_menu.rs
src/menu/ide_menu.rs

fix: accurately locate the match within the suggestion value

---

src/engine.rs

Reedline will batch KeyEvents when they arrive in quick successions. It then further accumulates edit events into a single edit event. This allows it to only perform a single repaint for the whole batch, instead of always needing one repaint per event. However, as of now, events which aren't edit event, such as arrow key presses, still trigger one repaint per event. This commit will change that, and always repaint once at the end of the batch (if a repaint is needed).
- fixes #914

Only repaint at the end when processing a batch of events

---

src/menu/columnar_menu.rs
src/menu/ide_menu.rs

This fixes https://github.com/nushell/reedline/issues/919 see the issue for a full description
I see a lot of discussion about newer code coming related to fuzzy matching, so this is just to temporarily fix the immediate issue of the panic. I think the most useful thing here is the addition of the test case to catch it.
I wasn't sure if I should handle the match_position = 0 case specially, or modify match_len to mean characters, not bytes. I went with the latter as I thought it looked cleaner, but there's definitely an argument for keeping the old code path for the majority of cases.
This is my first PR, very open to any feedback. Did my best but there's a lot of guidelines to absorb and I don't know most of the code base.

Fix panic when using fuzzy completion in a folder containing files starting with a multibyte unicode char

---

src/menu/columnar_menu.rs
src/menu/ide_menu.rs
src/painting/painter.rs
src/painting/prompt_lines.rs

currently when scrolling up, the selected item will always stick to the bottom (see #733)
This PR fixes that.
Currently implemented for
* ide menu
* columnar menu
closes #733

Add smooth scrolling to menus

---

src/painting/painter.rs

fix: adjust cursor start position for large buffers

---

src/edit_mode/base.rs
src/edit_mode/vi/mod.rs
src/engine.rs
src/enums.rs

Closes #499.
This PR adds the `ViChangeMode` event. Making it possible to change the mode using the normal event system. To achieve this, a new optional function `handle_mode_specific_event` was added to the `EditMode` trait. Vi mode implements this function and handles the event to change the mode accordingly. 
This will make it very easy to add the possibility of configuring mode-change keybindings in nushell.
Here's an example of how it could look:
```
{
name: exit_insert_mode_with_ctrl_c
modifier: control
keycode: char_c
mode: vi_insert
event: {
send: vichangemode
mode: normal
}
}
```
I plan on submitting a PR to nushell if this gets merged to add the functionality there too.
The main difference with #670 is that PR makes it user-configurable instead of it being a hard-coded value.
As …

feat: add `ViChangeMode` event

---

examples/custom_prompt.rs
examples/transient_prompt.rs
src/menu/menu_functions.rs
src/painting/utils.rs
src/prompt/base.rs
src/prompt/default.rs

From Rust 1.89.0 on this lints.
https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint

Fix `mismatched_lifetime_syntaxes`

---

README.md

Hey! I was looking at the instructions and noticed this was missing to have it compile. There was a correct example [here](https://docs.rs/reedline/latest/reedline/index.html#integrate-with-custom-tab-completion) though

Fix missing use in README.md

---

src/lib.rs
src/menu/columnar_menu.rs
src/menu/mod.rs

An attempt to fix https://github.com/nushell/reedline/issues/928 by making columnar menu traversal direction configurable.
```rust
ColumnarMenu::default().with_traversal_direction(TraversalDirection::Horizontal)
```
```rust
ColumnarMenu::default().with_traversal_direction(TraversalDirection::Vertical)
```
I've prepared changes for exposing this setting to the `nushell` configuration (currently at https://github.com/simonborje/nushell/commit/e42a31d4f9acaae77dd3b8b32741be9c9aab61be) that I can post as a PR if this change is accepted.
I've tested these changes manually using `nushell` with the configuration patch mentioned above. It seems to work as I intended in the scenarios I have tried, but there might be situations where something goes wrong.
I'm not sure what the best name for the …

feat: make columnar menu traversal direction configurable
