nushell/reedline

src/line_buffer.rs

Change unicode example

---

src/line_buffer.rs

Removed need to collect grapheme indices into a `Vec`. Also, we can slice
the buffer from or to the insertion point to not have to iterate through
all of the indices.

Improve inc/dec of insertion point

---

src/main.rs

Also hides unused modifiers field.

Remove rundant exit function.

---

src/engine.rs
src/main.rs

Allow the engine to have its own `read_line`, which is responsible for returning the line of input the user gives it.

Allow the engine to read lines

---

src/engine.rs

Add binding for Ctrl+n and Ctrl+p

---

src/engine.rs
src/line_buffer.rs

This removes the need for `get_buffer()` everywhere.

Implement Deref for LineBuffer

---

Cargo.lock
Cargo.toml
README.md
src/clip_buffer.rs
src/engine.rs
src/history.rs
src/history_search.rs
src/lib.rs
src/line_buffer.rs
src/prompt.rs

Includes some doc tests for the `History`. Code examples for `Reedline` are still very bare bones. 
Some of the APIs probably subject to significant change

Basic API docs to give an overview of the current state

---

src/engine.rs
src/lib.rs
src/main.rs
src/prompt.rs

Added support for automatically changing the prompt color.

Add dynamic prompt color

---

README.md
TODO.txt
src/engine.rs
src/history.rs
src/keybindings.rs
src/lib.rs
src/main.rs

This adds a few features from the latest stream:
* Allows keybindings to be user-configurable
* Adds support for setting up the history and keybinding using the builder pattern
* Properly truncates history file to the history length
* Adds a vi mode with some initial normal/insert mode commands

Vi mode and more

---

src/engine.rs

* Fix the infinite scrolling with cursor in the last line. 
* Use the return values of `.full_repaint()`
* Handle more than one linewrap
* Hide cursor on `.full_repaint()`
* Handle resizing better (not all cases are handled)

fix: prompt_origin and prompt_offset issues

---

src/lib.rs
src/prompt.rs

Simple bug fix with use declaration and public scope, it should be straightforward to approve, thanks.

Bugfix after recent changes in prompt module

---

src/engine.rs
src/highlighter.rs
src/lib.rs
src/main.rs

Hey everyone, I added this new feature that allows you to change the color of the buffer if the command is recognized or not, obviously I have implemented it so that it is backwards compatible adding default values and customizable for those who have this need. 
I will post here a little gif so you can understand better.

Feature buffer color

---

src/engine.rs
src/painter.rs

As per our discussion - https://discord.com/channels/601130461678272522/855886335980994600/860066323819003924

Highlighter in painter

---

src/completer.rs
src/engine.rs
src/lib.rs
src/line_buffer.rs
src/main.rs

Initial commits for adding the autocomplete feature; I would need to understand how we want to recognize the tab event and especially how to recognize multiple tabs event in series to go on with the suggestions; let me know if you have some ideas

[Add] first implementation of auto completion

---

README.md
src/lib.rs

Changes:
1. Removed duplicate documentation in lib.rs 
2. Updated readme file with latest improvements and changes

[StyleFix][Update] Documentation

---

UX_TESTING.md

As some bugs are hard to find with automated tests, we should regularly
test the core behavior of reedline, to catch those bugs that might creep
in, when changing the I/O, frontend or core code.
I am looking for suggestions on how we make this manual checklist
comprehensive enough to cover most problems but not too tedious to do
manually. (Ideally we find a way to integration test most of it)

Manual checklist to test the UX

---

src/engine.rs
src/history/file_backed.rs

Change cursor pos in prefix search to the end

---

.gitignore

Very fast change to ignore DS Store on MacOS, should be immediate to approve.

[Improve] gitignore file adding MacOS ds_store

---

src/completer.rs
src/engine.rs
src/line_buffer.rs

A very small PR that hides the implementation details of line_buffer. Now no one knows how line_buffer is tracking insertion point.

Outside world does not know about insertion point

---

src/engine.rs

Quick style fix from my latest PR

[StyleFix] compact engine.rs match arms

---

src/edit_mode/emacs.rs
src/edit_mode/vi/mod.rs
src/validator.rs

Added check for incomplete brackets

Incomplete brackets

---

src/enums.rs
src/history/base.rs
src/history/file_backed.rs
src/lib.rs

Simplify and document history trait

---

src/main.rs

Inform about the character code and the bit pattern of the modifier to
debug more subtle problems with key events
Prompted by #169

Provide more details in the keyevent debugger

---

src/edit_mode/emacs.rs

As requested in #169, a fix for the curly braces problem!

Curly braces fix

---

src/main.rs

Small printing bug introduced due to raw mode had to be fixed

Fix printing of #170

---

src/edit_mode/emacs.rs
src/edit_mode/vi/mod.rs

Curly braces fix in vim events

---

Cargo.lock
Cargo.toml
src/engine.rs
src/hinter.rs
src/main.rs
src/painter.rs
src/styled_text.rs

`with_ansi_colors(false)`
`with_ansi_colors(true)`

add the ability to optionally turn off ansi coloring

---

src/engine.rs

Currently, in reedline if you're at the bottom of the terminal and type until it wraps around the terminal edge you can create a buffer that if you hit enter and then up to recall the history, any character you type after this point will scroll the terminal.
This PR does some wrapping estimation that we can use to adjust the prompt position.

Add some wrapping estimate when adjusting prompt

---

src/engine.rs

This should allow you to paste text with returns in it, and get a multiline edit as a result.
It also removes some of the crashes if you paste a large paste that scrolls the prompt off the top of the screen.

Multiline fixes

---

src/edit_mode/vi/mod.rs

Same idea. Every new line should start in insert mode

vi insert mode kept after enter

---

src/completion/base.rs
src/completion/default.rs
src/core_editor/clip_buffer.rs
src/edit_mode/base.rs
src/engine.rs
src/highlighter.rs
src/hinter.rs
src/history/base.rs
src/prompt.rs
src/validator.rs

fix: make traits `Send`

---

src/styled_text.rs

Make the contents of StyledText pub to make it easier to work with

Make StyledText easier to work with

---

src/core_editor/line_buffer.rs

- current line detection was off on the first position of a following
line
- find_current_line_end was not correctly aware of CRLF platforms
- Increase of coverage for some old functions

Test and fix line buffer utils

---

src/painter.rs

There were repetition when inserting text in the middle of a multiline buffer. This should correct it

adjust position to insert in middle

---

src/engine.rs

Let anims handle resize

---

src/core_editor/editor.rs
src/engine.rs
src/painter.rs

In our required line estimator, also estimate the additional lines created when a long line wraps around the edge of the screen.

Estimate wrapping

---

src/engine.rs
src/main.rs
src/painter.rs

Input of buffer larger than screen size

Big buffer

---

src/main.rs
src/painter.rs
src/prompt.rs

based on #240 with the addition of line width estimate

Double prompt

---

src/core_editor/line_buffer.rs
src/edit_mode/keybindings.rs
src/engine.rs
src/enums.rs

We can add additional support for tab and hints in the future, but I think the first task is to disambiguate hints and completions. In fish, right arrow does a full hint completion, so let's start with that.

Right arrow is full hint completion

---

src/engine.rs

Hide hint when finishing line entry

---

src/context_menu.rs
src/engine.rs
src/painter.rs
src/prompt.rs

- reduces number of calls to completer to improve performance
- introduces new indicator for when the menu is active

menu performance

---

src/edit_mode/keybindings.rs
src/engine.rs
src/enums.rs
src/lib.rs
src/main.rs
src/menu/context_menu.rs
src/menu/history_menu.rs
src/menu/mod.rs
src/painter.rs
src/prompt.rs

Introduces a Menu trait that can be used to create menus for reedline

Generic menus

---

src/engine.rs
src/menu/completion_menu.rs
src/menu/history_menu.rs
src/menu/mod.rs
src/painter.rs

Dynamic menu that adjusts the size of the page based on how many lines can be printed in the terminal

dynamic menu

---

Cargo.lock
Cargo.toml
src/completion/default.rs
src/core_editor/editor.rs
src/edit_mode/base.rs
src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs
src/enums.rs
src/history/base.rs
src/history/file_backed.rs
src/internal/mod.rs
src/internal/query.rs
src/lib.rs
src/main.rs
src/menu/completion_menu.rs
src/prompt.rs

This is a quick hack to list things. It's totally meant as a conversation starter and not a finished implementation. Feel free to hack on and submit to this PR.
If this was to be used exclusively to pass information to e-q we could `impl Display for blah_enum` and output the text that the keybindings in e-q want to see when parsed. I prototyped that here too.
I'm thinking something like this needs to be turned into several exposed functions so that, in e-q, we can call `get_modifiers()`, `get_modes()`, `get_keycodes()`, etc. and show them to the user so they know what is map-able via keybindings.
```rust
impl Display for PromptEditMode {
fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
match self {
PromptEditMode::Default => write!(f, "default"),
PromptEditMode::Emacs => write!(f, …
```

list things with `reedline --list`

---

Cargo.lock
Cargo.toml

Move to latest crossterm (currently on git)

Move to crossterm on git

---

src/engine.rs
src/main.rs

Avoids extra partial completions when comparing strings

Partial completions

---

src/engine.rs
src/menu/completion_menu.rs
src/menu/history_menu.rs
src/menu/mod.rs

Clean menu code for partial completion and corrected bug from history menu

menu partial completions to menu function

---

src/menu/history_menu.rs

Corrects a history menu error and panic

history menu page error

---

src/engine.rs
src/menu/history_menu.rs
src/menu/mod.rs

Allows this `!-2` for history completion

backward history bang

---

Cargo.lock
Cargo.toml

- Update dependencies
- Increase version number to 0.3.0

Prepare for new release

---

src/edit_mode/emacs.rs

add missing alt-f for parity with the existing alt-b

---

src/menu/menu_functions.rs

Fix `menu::menu_functions::string_difference` returning wrong substring or even panicking when given non-ASCII strings.

Fix `menu::menu_functions::string_difference`

---

README.md

The example in the read me doesn't actually run until you add a return value for propagating io results.

Fix the first example in the readme so it can be run

---

src/menu/completion_menu.rs

aligns suggestions descriptions to the left

format descriptions to the left

---

.github/workflows/ci.yml
Cargo.toml
src/engine.rs
src/menu/menu_functions.rs

Moved all bashisms behind a feature flag
Added `!$` to get the last token from the last command run

bashisms feature for reedline

---

src/engine.rs

Escape Ctrl-R history search with `ESC`

---

src/menu/columnar_menu.rs

Reduces the size of the descriptions to fit the actual column length

short descriptions

---

src/menu/columnar_menu.rs

Short description

---

src/prompt/base.rs

this is for my good friend @stormasm

change dark orange in prompt to purple

---

src/edit_mode/vi/command.rs
src/edit_mode/vi/parser.rs

I have successfully made the changes you proposed.

Add vim's `C` binding

---

.github/workflows/ci.yml

This tries to replicate the cargo caching techniques developed by @rgwood on the [nushell](https://github.com/nushell/nushell) repo to save time (and energy) on the CI pipeline.
[Reilly's blog post](https://www.reillywood.com/blog/rust-faster-ci/)

Change the CI to use caching

---

src/completion/base.rs
src/completion/default.rs
src/completion/history.rs
src/menu/columnar_menu.rs
src/menu/list_menu.rs
src/menu/menu_functions.rs

Signed-off-by: gipsyh <gipsyh.icu@gmail.com>

Append whitespace after selecting menu

---

src/edit_mode/emacs.rs
src/edit_mode/keybindings.rs

* Move ctrl+d keybinding from emacs to common keybinds
* Move ctrl+w keybinding from emacs to common keybinds

Move some commonly used keybinds to common keybinds

---

src/completion/base.rs
src/core_editor/line_buffer.rs
src/menu/columnar_menu.rs
src/menu/menu_functions.rs
src/painting/styled_text.rs

clippy from the nightly future

Fix clippy lints that will become warnings

---

Cargo.lock
Cargo.toml

Update nu-ansi-term/update crate patch versions

---

Cargo.lock
Cargo.toml

Includes the new History API and their backends

Prepare 0.7.0 release

---

src/history/item.rs

adds the ability to get the HistoryItemId and HistorySessionId and use .to_string() on them.

add impl Display to HistoryItemId and HistorySessionId

---

src/menu/columnar_menu.rs

Avoid subtraction overflow when using usize.

---

src/edit_mode/vi/command.rs
src/edit_mode/vi/mod.rs

Just to keep CI happy in the future

Clippy fix for tests

---

Cargo.lock
Cargo.toml

- Prepare 0.12.0 release
- Widen author metadata

Prepare 0.12.0 release

---

examples/basic.rs
examples/completions.rs
examples/highlighter.rs
examples/hinter.rs
examples/history.rs
src/main.rs

This PR covers all examples except "custom keybindings", however in the "completions" example a custom keybinding is exemplified.
Let me know if you think it is worth merging in current state or if some further changes are needed.
/Per

examples updated

---

README.md
examples/completions.rs
src/lib.rs

Adapted from examples added in #493

Fix completion example in README/lib.rs

---

CONTRIBUTING.md

Just fixing the example (`cargo run` doesn't work anymore)

Fix example in CONTRIBUTING.md

---

README.md

see https://github.com/badges/shields/issues/8671

Fix the Github actions badge

---

examples/demo.rs
src/engine.rs

I added this to help Reilly debug a problem. It didn't help find the problem but thought it may be something good enough to stay in the demo.

add history-clear to demo

---

Cargo.lock
Cargo.toml

https://github.com/la10736/rstest/blob/master/CHANGELOG.md

Bump `rstest` to 0.16

---

src/core_editor/clip_buffer.rs
src/history/cursor.rs
src/prompt/base.rs

Apply clippy lints

---

Cargo.lock
Cargo.toml

See release notes:
https://github.com/nushell/nu-ansi-term/releases/tag/v0.47.0

Update `nu-ansi-term` to 0.47.0

---

Cargo.lock
Cargo.toml

Bump version for `0.17.0` release

---

src/edit_mode/base.rs
src/edit_mode/mod.rs
src/lib.rs

Make `Event` public to allow implements custom `EditMode`

---

src/core_editor/editor.rs
src/edit_mode/emacs.rs
src/history/base.rs
src/history/cursor.rs
src/history/item.rs
src/painting/styled_text.rs
src/prompt/base.rs
src/prompt/default.rs

Constify the applicable new functions.
There are a lot more functions that could be constified. But I prefer to do it: step by step where it makes sense.
PS: I already did some tests in local, and adding const to some functions unlock the constification to more functions.

Add const to some new functions.

---

examples/demo.rs
src/edit_mode/emacs.rs
src/edit_mode/vi/mod.rs
src/engine.rs

Closes: #543
Fixes: #558
Once it's ok, we can make nushell support bracketed paste easily :-)

support bracketed paste

---

src/engine.rs

Fix clippy lint for DoubleEndedIterator

---

src/core_editor/editor.rs
src/core_editor/line_buffer.rs

Fix big_word_left_index

---

Cargo.lock
Cargo.toml

Bump version for 0.23 release

---

Cargo.lock
Cargo.toml
examples/demo.rs
examples/event_listener.rs
examples/event_listener_kitty_proto.rs
examples/list_bindings.rs
src/engine.rs
src/painting/painter.rs

Waiting for nushell as ratatui (used in nu-explore) is still on 0.26

Bump `crossterm` to 0.27.0

---

.github/workflows/ci.yml

See: https://github.com/actions-rs/toolchain/issues/216

Remove old `actions-rs/cargo`

---

examples/ide_completions.rs

I am adding some more test cases to this example so the end user can explore more options to see how the example
works...   These test cases are similar to the ones found in the demo example...

update the ide_completions example with more cases to explore

---

src/menu/columnar_menu.rs

columnar_menu: fix explicit highlighting color

---

src/painting/styled_text.rs

Fixes https://github.com/nushell/reedline/issues/750#issue-2127609999

Fix logic error in style_range leading to overflow on subtraction

---

src/edit_mode/vi/mod.rs

Revert "Move left when exiting insert mode"

---

Cargo.toml
src/core_editor/clip_buffer.rs
src/menu/description_menu.rs

fix some new clippy warnings

---

.github/workflows/ci.yml
Cargo.lock
src/engine.rs
src/menu/ide_menu.rs

@fdncred fixup something when debugging ..

chore: ensure lockfile up-to-date

---

src/engine.rs

Closes https://github.com/nushell/reedline/issues/757

Fix external printer don't print until key press

---

Cargo.lock
Cargo.toml

Bump version for 0.40.0 release
